### ISSUE TITLE
Abstract socket address for IPC

### ISSUE THREAD

**Issue by ravone** [nanomsg/nng#1041]
How to specify abstract socket address in URL for IPC transport as per `man 7 unix`:
> abstract:  an abstract socket address is distinguished (from a path‐
>           name socket) by the fact that sun_path[0] is  a  null  byte  ('\0').
>           The  socket's  address  in this namespace is given by the additional
>           bytes in sun_path that are covered by the specified  length  of  the
>           address structure.  (Null bytes in the name have no special signifi‐
>           cance.)  The name has no connection with filesystem pathnames.  When
>           the  address of an abstract socket is returned, the returned addrlen
>           is greater than sizeof(sa_family_t) (i.e., greater than 2), and  the
>           name   of   the   socket  is  contained  in  the  first  (addrlen  -
>           sizeof(sa_family_t)) bytes of sun_path.

**Comment by gdamore** [comment]
I'm aware of that -- but today NNG doesn't offer abstract addresses, partly because the abstract address specification requires NULL bytes -- making it difficult or impossible to supply this in a URL.

What I might do is create a new "transport", "abstractipc://" or something, that just prefixes the path with a null byte and uses the rest of IPC under the hood.

This hasn't been a very high priority, as this form of IPC is only usable on Linux, and while it solves one problem (cleaning up file system paths), it suffers from others (for example, abstract paths are completely unsecured, making them available to any user of the system.)

At any rate, abstract IPC is still a requested enhancement.

**Comment by ravone** [comment]
In my opinion, using prefixes is more convenient and simpler way. I found that `@` symbol [is used for this](https://unix.stackexchange.com/questions/206386/what-does-the-symbol-denote-in-the-beginning-of-a-unix-domain-socket-path-in-l). ZeroMQ [uses it too](https://github.com/zeromq/libzmq/blob/805564b996ff7eba518c95eef6bff7a7de5a0364/src/ipc_address.cpp#L84), for ex. `ipc://@/myproc/data`

**Comment by gdamore** [comment]
Ah right, I'd forgotten about that syntax.  Yeah , I can do that.

**Comment by ravone** [comment]
@gdamore Can I make pull request for this issue?

**Comment by gdamore** [comment]
You can.

**Comment by ravone** [comment]
I'm working on it.

**Comment by gdamore** [comment]
I'm watching for your PR.  If you don't get something together in the next week or so, I'll probably knock one out.  I don't think it should be too bad to do.

**Comment by gdamore** [comment]
I'm moving this out to 1.4.  I want to get 1.3 out asap.
