### ISSUE TITLE
Re-using buffers when sending messages

### ISSUE THREAD

**Issue by Bigpet** [nanomsg/nng#1119]
I just wanted to ask for clarification if there's really no way to send two messages with the same message body without either copying or allocating.

In the first scenario of trying to send the contents of a buffer message is allocated and copied twice
```
    char buffer[1000] = {};
    //fill buffer
    nng_send(sock, buffer, 1000, 0);
    nng_send(sock, buffer, 1000, 0);

```

Trying to circumvent this with `nng_sendmsg` I could still not send two messages without allocating a messagebody

```
    nng_msg* msg = NULL;
    nng_msg_alloc(msg, 1000);
    //fill data into nng_msg_body
    nng_sendmsg(sock, msg, 0);
    //ownership transferred, need to re-allocate
    nng_msg_alloc(msg, 1000);
    //fill data into nng_msg_body
    nng_send(sock, buffer, 1000, 0);

```

I understand trying to prevent memory leaks by clearly transfering "ownership". Also headers needing to be re-allocated is understandable. But for larger message-bodies it seems sort of useful to be able to re-use allocated memory.

Is this something already possible with nng? Would you consider this feature or is it somehow anathema to some design goals of the library or protocol?

**Comment by gdamore** [comment]
I've implemented this in mangos (the Golang analog), and I've already looked at doing this for NNG.

The only way to make this work is to have an nng_clone() or similar call, that indicates that I am taking a read-only copy of the message, then an nng_unclone() or nng_fork() or something similar call that applications use to ensure that they have the sole copy of a message before modifying (basically doing a copy-on-write).  This can also be done separately for the message headers and message bodies.)

My plan of record was to do this automatically under the hood for PUB/SUB and similar protocols that are making copies today -- the application wouldn't need to be aware of it.  I was not planning on providing this capability in our *public* API, but I might be convinced to do so given a compelling use case.

**Comment by Bigpet** [comment]
Well my usecase was more of a semi-realtime application and I had a ringbuffer that regularly multi-megabyte chunks would be requested from. Not needing to copy would be a real advantage there specifically because the memory bandwidth is already under quite some pressure.

My immediate solution would have been to abuse the storage of `m_pipe::m_pipe` for flags in sending messages to prevent it from deleting the msg_body storage. But I don't fancy making changes and then leaving them in an unmaintained fork.

Maybe that is a little too niché to consider. I was planning on only using one-to-one pipes in any case. I'm probably better served with just a tcp socket. The reason I considered nng was just to cut down on boilerplate.

**Comment by gdamore** [comment]
The use case you want is actually a little different -- its a want for a zero copy for special memory arenas.  That's quite different from the concern about fan out copies, but more about minimizing data copies for even unicast streams.   Rather, your use case is typical of ideas around shmem IPC, or RDMA.

I'd like to offer those, and have thought a bit about it -- basically applications that need this for *extreme* bandwidth are probably going to have to pay some penalties in complexity because there will be effort -- they will have to register a destructor on the nng_msg_t, which will be called when the framework determines its wants to free the message.  Then the application can decide what to do with the memory.

There is no question that right now if you're truly constrained by memory bandwidth (I'd be skeptical of that btw, unless you're doing extreme amounts of data -- 10s of Gbps typically -- you probably aren't under memory bandwidth pressure), you should probably just use TCP, and maybe even consider RDMA or similar options to reduce copying even into kernel memory (there might also be tricks you could try with sendfile() or similar to page flip memory across the kernel/user memory boundary instead of copying it).  Right now, these are fairly far outside the design center for NNG.

**Comment by gdamore** [comment]
One important point --- you're going to  pay for that copy across the kernel/user space unless you do something unusual.

**Comment by Bigpet** [comment]
Thanks, for the advice. I'm talking about fetching and doing processing (that's not compute bound) on image data from a PCIe attached camera sensor.

The nng connection would be over a network protocol in any case since this is across devices, so there's no additional overhead from TCP that I would not pay with nng (since RDMA is not a good choice for this project specifically).
