### ISSUE TITLE
CBOR to the transport layer

### ISSUE THREAD

**Issue by edbek** [nanomsg/nng#113]
How about adding the CBOR protocol to the transport layer?

**Comment by Crest** [comment]
Have you read the spec? Do you want to deal with 65 bit signed integers?

**Comment by gdamore** [comment]
CBOR is not a transport layer.  It's an encoding method, and totally orthogonal to nng.  nng sends byte arrays -- i.e. binary data.  You can use it to send CBOR, msgPack, HTML, mime64, GB18030 strings, or whatever else you might desire.  nng and nanomsg will always remain agnostic about data types.

(That said nngcat -- following nanocat's example -- does encode data from the command line and send it.  This isn't intrinsic to nng, but merely a convenience for shell users.  Honestly, I'd rather people didn't use that, and built real applications instead.)

Closing this for now.  If you want nngcat to handle CBOR for some reason, file a separate issue, and I will look at it.  (Low priority though -- because adding new encoding methods is definitely very low priority, especially given the large number of potential encodings we "could" in theory support.)

**Comment by edbek** [comment]
How can I use nng in the event that two processors are interconnected by a RS-232 or UART interface ? Thankful in advance for the answer.

**Comment by Crest** [comment]
There are two alternatives make the serial connection usable for an existing transport (e.g. run PPP over it or proxy unix sockets) or implement your own transport.

**Comment by gdamore** [comment]
If you don't already have PPP or SLIP (and hence lack IP), you may just want to build your own... I'm not sure why you'd even need or want nng over that kind of a single peer-to-peer hardwired connection, but I'd look at the TCP transport -- basically it sends a single 64-bit length for the message size, then the actual message.  (It does send a little more during establishment though -- such as the nanomsg protocol number.)
