### ISSUE TITLE
Do Bus/Survey no longer support NNG_OPT_LOCADDR?

### ISSUE THREAD

**Issue by jeikabu** [nanomsg/nng#1137]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

Starting with v1.2.0, still present in v1.2.4.  Verified on: Windows 10/Server, Ubuntu 18.04.

## Expected Behavior

In v1.1.1, any of the protocols could listen on `tcp://localhost:0` and then use `NNG_OPT_LOCADDR` to get the port number.

## Actual Behavior

Starting v1.2.0, in the returned `nng_sockaddr` for both bus0 and survey0 protocols, `s_family` is `NNG_AF_UNSPEC`.  Seems to be fine with all other protocols.  Not sure if this is a bug, or intentional/desired behavior.  Doesn't seem to matter if you start the listener or not.

## Steps to Reproduce

```c
#include <nng.h>
#include <protocol/bus0/bus.h>
#include <protocol/survey0/survey.h>
#include <stdio.h>
#include <assert.h>

int main(int argc, char** argv) {
    const char* url = "tcp://localhost:0";
    nng_socket socket;
    nng_sockaddr addr;
    nng_listener listener;
    
    assert(nng_bus0_open(&socket) == 0);
    assert(nng_listener_create(&listener, socket, url) == 0);
    assert(nng_listener_getopt_sockaddr(listener, NNG_OPT_LOCADDR, &addr) == 0);
    assert(nng_listener_start(listener, 0) == 0);
    printf("Family=%d\n", addr.s_family);

    assert(nng_surveyor0_open(&socket) == 0);
    assert(nng_listener_create(&listener, socket, url) == 0);
    assert(nng_listener_getopt_sockaddr(listener, NNG_OPT_LOCADDR, &addr) == 0);
    printf("Family=%d\n", addr.s_family);
    return 0;
}
```

**Comment by gdamore** [comment]
It's weird that it would be protocol specific.  There is nothing protocol specific there that I'm aware of.

Note however in the code above, you can't get a meaningful answer back from NNG_OPT_LOCADDR until *after* you call nng_listener_start().  That's because until that point the listener is not yet bound, and we don't have any idea what the TCP port number the system will give us will be (particularly when you are using port 0 to mean  "any port").  Arguably we could probably give back a good answer for non-wildcard addresses, but that would be kind of a lie, since the port isn't in use yet.

Think of this like TCP sockets getsockname()  (that's how it is implemented anyway).  It only works once you've actually bound.  For nng_listeners, that happens when you start them.

**Comment by jeikabu** [comment]
Makes sense.
Turns out had slightly different tests for bus/survey.  Moving getopt after start does the trick, not sure why it worked before.
