### ISSUE TITLE
Closing nng_aio in aio callback

### ISSUE THREAD

**Issue by ev-ermakov** [nanomsg/nng#1138]
Hello. What is the best practise to close `nng_aio` when it is no longer needed? For example, when `nng_aio_result()` returns an error like `NNG_ECONNSHUT`. If I call `nng_aio_free()` directly, a deadlock occurs.

**Comment by gdamore** [comment]
If you're getting a deadlock, its because you are trying to do that from the callback that you registered for the aio.  You can't do that.  You have to arrange for the finisher to be done from another thread, such as your main thread.

If you only have a few of these in your program, then I would not worry about cleaning them up -- they consume only a few hundred bytes each.  If you have lots and lots of them, it's trickier, and you might want to set up some some kind of thread to reap them asynchronously if you have no other solution.  Usually in that case you will also have some kind of other state object (such as application state or something) that you need to free as well.  It's very very important that you don't for instance destroy (free) any private state that the callback might be using until *after* the aio has been properly stopped with either nng_aio_stop or nng_aio_free.

(There's also an nni_aio_close, but I'm not sure there is a public API version of that -- which does the process of stopping any current or future activity, without waiting for that activity to finish.  It does not free up the resources though.)

Addressing the best way to do this is kind of complex, unfortunately, and its pretty specific usually to the details of your application and how you are going to manage the state for it.

**Comment by ev-ermakov** [comment]
Thanks for the advice. I decided to use a separate thread to free state objects.

**Comment by ev-ermakov** [comment]
@gdamore , is it possible to use  `nni_reap()`?

**Comment by gdamore** [comment]
Unfortunately i did not make that api public.  Maybe I should.

Garrett D’Amore

________________________________
