### ISSUE TITLE
resolv test failed on alpine linux image

### ISSUE THREAD

**Issue by chainhead** [nanomsg/nng#1149]
While building with `alpine:latest` Docker image, the `resolv` test failed. How do I get around this?

```bash
The following tests FAILED:
Errors while running CTest
	 30 - resolv (Failed)
FAILED: CMakeFiles/test.util 
cd /build && /usr/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
```

**Comment by gdamore** [comment]
That test requires that you are on an internet connected system with access to functional DNS.  It also requires that you have IPv6 set up.  If you run the test by hand with "-v" then you'll see what actually failed, but most likely the environment you are running in doesn't support the preconditions of the test.

That's not actually a problem if you don't need DNS resolution or aren't using IPv6 in your environment.

**Comment by chainhead** [comment]
> That's not actually a problem if you don't need DNS resolution or aren't using IPv6 in your environment.

Correct.

Is there a way to get around that particular test; so that I have clean build, test and install?

**Comment by gdamore** [comment]
Unfortunately, I didn't plan on disabling specific tests.  You can just ignore that particular test failure if you like.   That's what I would recommend.

Maybe we should create some kind of "skip" environment variable.  I will see if I can come up with something.  (I already have an environment variable that skips the IPv6  portion for Travis and Circle CI because those environments don't support IPv6.)

**Comment by chainhead** [comment]
> Maybe we should create some kind of "skip" environment variable. 

That would be nice! 

This question is in relation to #1148 .

**Comment by gdamore** [comment]
For that use case, you could just skip the tests altogether.

There are some cases where the tests themselves fail due to fragility in the test suite rather than in the library, so I would not normally encourage anyone to build running our test into their own product pipelines.  (I do run them as part of my pipeline, but I examine test failures and basically waive the few that I know are a bit dodgy due to different timings in various clouds, etc.)

**Comment by chainhead** [comment]
Do you have contribution guidelines that I can go through? I am mostly done with a working `Dockerfile` for `nng` on `alpine:latest`.

**Comment by gdamore** [comment]
I'm not terrifically interested in a Dockerfile here, because I don't use Docker myself.  (I know, heresy....)

We do use just a normal PR process.  So feel free to submit a PR.

I'm going to close this particular issue for now, because your question was answered.
