### ISSUE TITLE
Add missing ::nng_pipe_getopt_usec implementation

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#116]
As far as I know I've pulled from ``HEAD`` during my *CMake* build.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol nng_pipe_getopt_usec referenced in function "public: virtual void __cdecl nng::messaging::message_pipe::get_option_usec(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned __int64 *)" (?get_option_usec@message_pipe@messaging@nng@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEA_K@Z)	inproc	G:\Source\Spikes\nanomsg\cppnngswig-working\build\swig\cpp\tests\nngcpp.lib.lib(message_pipe.obj)	1	
```

In the ``nng.h`` header file:

```C
NNG_DECL int nng_pipe_getopt_usec(nng_pipe, const char *, uint64_t *);
```

But in the ``nng.c`` file, looks like possible a copy/paste oversight to me.

```C
int
nni_pipe_getopt_usec(nng_pipe id, const char *name, uint64_t *valp)
{
	return (nng_pipe_getopt_uint64(id, name, valp));
}
```

I'll throw my internal ``trx::not_impemented`` for now until it's fixed.

**Comment by gdamore** [comment]
Yep... looks like it should be nng_pipe_getopt_usec.

**Comment by gdamore** [comment]
FYI, I am probably going to deprecate the usec options in favor of ms (milliseconds).

I've pretty well decided that milliseconds are a lot easier for most folks, and usec resolution timeouts (which is the only thing these are used for) offer no real value.

**Comment by mwpowellhtx** [comment]
Excepting for embedded, real-time systems.

**Comment by gdamore** [comment]
Actually, even for those systems, their clock is usually limited to msec resolution; and even on those systems there is little call for a nanomsg-style timeout of sub-ms resolution.  Put another way, nanomsg/nng transports really don't work in sub-ms time reliably, such that I would not recommend using a <1ms timeout anywhere.

**Comment by mwpowellhtx** [comment]
I was running on an ARMv5 I believe at the time, using ArchLinux, and I was experiencing high resolution microseconds performance, not milliseconds.

**Comment by gdamore** [comment]
Yes, ARM has a high resolution counter, and modern embedded CPUs often have usec resolution - useful for performance measurements.  That does not mean that they can meaningfully set usec timeouts.  Generally the resolution for event timers is around 1 msec.  Exceptions to that are unusual, and irrelevant to nanomsg or network protocols in general.  (You might make a case for this with some super performance infiniband network, but frankly because of the multithreaded and context switch driven architecture, we really should never be setting timeouts in sub ms. resolution.)

**Comment by mwpowellhtx** [comment]
Oh I see. That's a helpful bit of insight.
