### ISSUE TITLE
nng_sockaddr_in6 should support 32-bit and 16-bit unionized fields

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#119]
If I understand my blogs reading according to the [spec](http://en.wikipedia.org/wiki/IPv6_address) and the responses I've read, that's the layout, which does appear to care about network byte order. So while 16-byte array is interesting, it is virtually useless to work with.

See this [SO](https://stackoverflow.com/questions/15655574/converting-an-ipv6-type-address-to-network-byte-order) for more detail.

So, this:

```C
struct nng_sockaddr_in6 {
    uint16_t sa_family;
    uint16_t sa_port;
    uint8_t  sa_addr[16];
};
```

Should probably be something more like this:

```C
struct nng_sockaddr_in6 {
    uint16_t sa_family;
    uint16_t sa_port;
    union {
        uint8_t sa_addr8[16];
        uint16_t sa_addr16[8];
        uint32_t sa_addr32[4];
    } sa_addr;
};
```

Which, actually the 16-bit representation is probably most accurate according to the [statement](http://en.wikipedia.org/wiki/IPv6_address#Representation): *"An IPv6 address is represented as eight groups of four hexadecimal digits, each group representing 16 bits "*.

Oh, for fun with C/C++ *unions*.

Could be wrong.

**Comment by gdamore** [comment]
For all intents and purposes, the 16-bit array is in network byte order, and represents an IPv6 address fully.  If you need to convert these to some native representation, you have to do that using the appropriate API call... there is no standard for the "native" order (array of native 64-bit integers? native 32bit integers?  native 16bit ints?  And what order are the array elements in, btw?)

The native BSD sockaddr structure also uses native byte order, defining instead a struct in6_addr whose sole documented member is -- an array of 16 bytes.  See http://man7.org/linux/man-pages/man7/ipv6.7.html

In reality, unless you are writing some very low level IPv6 handling code (like the host stack itself), you really want to work with these 16-byte arrays (again network byte order), and when you provide them to humans (or convert from humans), you should be using the inet_ntop and inet_pton functions (which convert to printable form and vice versa).

You can quite naturally copy the sa_addr member from the nng_sockaddr_in6 to the sin6_addr member of struct sockaddr_in6 (and vice versa), and that's what they are meant for.

If you're doing something else, you're doing it "wrong", since you're going to have trouble dealing with the most typical socket APIs, including nng, winsock, and BSD sockets.

**Comment by mwpowellhtx** [comment]
@gdamore Bits? Or bytes? Just want to be clear here. Not according to what I'm reading about it.

The sentence, *"Both of them are in network byte order"* is ambiguous at best. ***What*** about them is in network byte order?

From what I've been reading, the 32-bit words themselves have the same ***htonl*** applied to them, for instance. At least that's my understanding based upon the blogs I've read, but I could be wrong. We'd need to vet that through more authoritative sources.

Or are we talking about all of the words, in network byte order, and reverse from the language level? I'm not too clear on that part.

**Comment by gdamore** [comment]
If you treat the address as a byte stream, network byte order is "big endian", which means that the most significant byte appears first.  (The order of individual bits within a single byte is determined by the physical media, but once it hits the computer the computer always presents bytes in the native bit order.  That is 128 is always logically 10000000b (binary).

For a 128-bit (i.e. 16 byte) address, if you were to treat the address as a single 128-bit quantity, the high order byte would be the most significant (e.g. take its value and shift it left by 120 bits to get the real value.)

The term network byte order is anything but ambiguous.  It is quite specific, and means what I've said. 

As a corollary, if you were to subset the 128-bit address into groupings (whether of 64, 32, or 16 bits) they would also be in network byte order.  The reasoning behind this is left as an exercise for the reader.

**Comment by mwpowellhtx** [comment]
@gdamore So, bottom line, would you be willing to add the 16-bit and 32-bit union view? But for naming conventions and usage, I pretty much did the work for you above.

Thanks!

**Comment by SG7** [comment]
I see nothing wrong with the union approach. It can be helpful.

Just one question: do we have to name the union? When left nameless there
is no impact on the rest of the code:

struct nng_sockaddr_in6 {
    uint16_t sa_family;
    uint16_t sa_port;
    union {
        uint8_t sa_addr8[16];
        uint16_t sa_addr16[8];
        uint32_t sa_addr32[4];
    };
};

**Comment by mwpowellhtx** [comment]
It's a good point. Perhaps not. It's clear, concise. Yep, indeed, and for existing code, you could even leave the bytes field unchanged, ``sa_addr``, for that matter, with 16-bit and 32-bit support available.

**Comment by SG7** [comment]
Yes, exactly. With structure presented below the current code compiles and
allows 16-bit and 32-bit support.

struct nng_sockaddr_in6 {

    uint16_t sa_family;
    uint16_t sa_port;
    union {
        uint8_t    sa_addr[16];
        uint16_t sa_addr16[8];
        uint32_t sa_addr32[4];
    };

};

**Comment by mwpowellhtx** [comment]
Great! Thanks for supporting that. It will be much easier to use ``htonl`` and ``htons`` with that.

**Comment by codypiersall** [comment]
I'm not sure how having this union helps things... I think it's going to create more problems than it solves.  I think it gives you lots of opportunities to shoot yourself in the foot.  It would be too easy to e.g. set the value via `nng_sockaddr_in6.sa_addr16` and then try to access the individual bytes via `nng_sockaddr_in6.sa_addr`.  If you're on a little-endian platform you may be unhappy about the results.

I'm not sure how this structure is used in nng, but I think it's a bug magnet to store this type as a union, since you could mistakenly accidently choose the wrong representation too easily.

As Garrett already metioned, if the motivation is to have the address in network order, the array of 16 bytes already accomplishes that.  Note that there is no function `htonc` (host-to-network-char)–it doesn't make sense to talk about the endian-ness of a single byte.

**Comment by mwpowellhtx** [comment]
There does not need to be an ``htonc``. Especially with ``htonl`` and ``htons`` being available, which is a good way to handle the issue. A byte array does have one upside; for loopback, you only have to access one byte, not the whole word, but even that is trivial with ``htonl`` and ``htons``.

**Comment by gdamore** [comment]
Honestly I am having a really hard time understanding why you need these
other union members. What value do they add?

**Comment by mwpowellhtx** [comment]
@gdamore As I explained, this would allow the consumer to leverage existing ``htonl`` and ``htons`` functionality.

@codypiersall Besides which, the whole structure from the parent on down is already a union.

For instance, notice how the ``s_family`` field works. This appears in the parent structure and in the parent structure as well as the unionized structures. Which using union magic is referring to the same memory, effectively. In other words, you've already resigned yourself to the consumer required to have (somewhat) advanced knowledge of how unions work.

**Comment by codypiersall** [comment]
@mwpowellhtx Why would the consumer need to call `htonl` or `htons`?  The bytes are already in network order when stored as an array of `uint8_t`.  Adding a union just gives a lot of room for confusing endian-ness bugs to creep in.  Here's a snippet of code so I can be precise about what I see as the problem here:

```#include <stdio.h>
#include <stdint.h>

struct nng_sockaddr_in6 {
    uint16_t sa_family;
    uint16_t sa_port;
    union {
        uint8_t sa_addr[16];
        uint16_t sa_addr16[8];
        uint32_t sa_addr32[4];
    };
};

int main() {
    struct nng_sockaddr_in6 s;

    // write via the uint32_t
    s.sa_addr32[0] = 0xdeadbeef;
    s.sa_addr32[1] = 0xba5eba11;
    s.sa_addr32[2] = 0xbaadc0de;
    s.sa_addr32[3] = 0x00ddba11;

    // read via the uint8_t
    for (int i = 0; i < 16; i++) {
        printf("%02X", s.sa_addr[i]);
    }
    printf("\n");
}
```

This code writes the values via the the 32-bit uint and prints them out with the 8-bit uint.  If you're running this on a little-endian system, your console will print out "EFBEADDE11BA5EBADEC0ADBA11BADD00", and not "DEADBEEF" etc.  Using a union here is just inviting this type of bug to crop in.  At a bare minimum, the union makes this code _way too easy to write._  At a minimum, if you use a union you need a flag to say what representation is actually valid, because **unless you are on  a big-endian platform only one representation will be valid.**

I'm not concerned about the consumer needing to know how unions work.  I'm concerned about how this complicates the API -- now I have 3 representations to choose from, only one of which is valid at any time on a little-endian platform.  And since most processors are little-endian, this is going to be a problem.

**Comment by mwpowellhtx** [comment]
Where is your call to ``htonl``? One isn't concerned about the host machine but rather the network byte order.

I'm not hung up on it one way or the other.

**Comment by mwpowellhtx** [comment]
@gdamore I would point out, this is not much different than your structure viewing the IPv4 address as a 32-bit unsigned integer, whereas structures like Windows sockaddr_in is defined as follows:

```C
typedef struct sockaddr_in {

#if(_WIN32_WINNT < 0x0600)
    short   sin_family;
#else //(_WIN32_WINNT < 0x0600)
    ADDRESS_FAMILY sin_family;
#endif //(_WIN32_WINNT < 0x0600)

    USHORT sin_port;
    IN_ADDR sin_addr;
    CHAR sin_zero[8];
} SOCKADDR_IN, *PSOCKADDR_IN;
```

And:

```C
//
// IPv4 Internet address
// This is an 'on-wire' format structure.
//
typedef struct in_addr {
        union {
                struct { UCHAR s_b1,s_b2,s_b3,s_b4; } S_un_b;
                struct { USHORT s_w1,s_w2; } S_un_w;
                ULONG S_addr;
        } S_un;
#define s_addr  S_un.S_addr /* can be used for most tcp & ip code */
#define s_host  S_un.S_un_b.s_b2    // host on imp
#define s_net   S_un.S_un_b.s_b1    // network
#define s_imp   S_un.S_un_w.s_w2    // imp
#define s_impno S_un.S_un_b.s_b4    // imp #
#define s_lh    S_un.S_un_b.s_b3    // logical host
} IN_ADDR, *PIN_ADDR, FAR *LPIN_ADDR;
```

But, like I said, I'm not hung up on whether NNG will provide that kind of flexibility in and of itself.

**Comment by codypiersall** [comment]
@mwpowellhtx Ah, I think I see where I was confused.  I thought you wanted to be able to put host-order bytes into the struct and only change them to network-order at system boundaries, but you actually only want network-order bytes to go into `nng_sockaddr_in6`.  That actually makes sense to me.  The docs should point out that only network-order bytes can go into the struct.

As long as the consumer always calls `htonx` when putting values in and `ntohx` when taking values out that works just fine.  Although I still don't know the use case, at least this isn't a bug magnet when it's clearly defined that you must put bytes into the union in network order.

**Comment by mwpowellhtx** [comment]
@gdamore For the fourth time, of course, yes.

**Comment by codypiersall** [comment]
@mwpowellhtx I think you meant to ping me there?

Sorry that I misunderstood, but honestly your first several posts read as though you thought the bytes being an array of uint8 was creating a problem with network order, which really doesn't make any sense.

Maybe if you provided a snippet of code where having the address defined as a union of these types helps your use case it would clear things up?  I'm not sure how much IP address manipulation actually needs to be done in nng so I'm kinda confused about a use case.

**Comment by mwpowellhtx** [comment]
@codypiersall It's impossible for me to know how it was read. That's not my responsibility here. I'm just presenting the facts and the case for some flexibility.

At any rate, I'm not hung up on it either way at this point. It would be nice for the flexibility, but I'll work around it if I have to.

**Comment by gdamore** [comment]
I saw your IPv4 post and yes conventionally stacks have treated IPv4
addresses as 32-bit words. However where this is typical for IPv4 it is
very atypical for IPv6. So much so that I have never seen IPv6 addresses
treated as arrays of 32-bit dwords. Maybe inet_ntop and pton do this (but
for 16-bit words) while converting to printable form but I have yet to see
an application do this in its own code. So much is this the case that most
platforms do not define the ip6_addr as anything but a byte array or
possibly a struct with only a single byte array member.

Of course I could add this union. I just think it would hinder both
readability and usability since then we have to have another dereference.
(Anonymous unions may not exist everywhere. )

So my question here is why do want to work on pieces of this address? In
fact why are you doing anything with it at all besides just copying it or
using it with inet_pton or inet_ntop? Convince me you have a use case and I
will reconsider; as of now I cannot imagine any use case for using htonl on
bits or pieces - unless you are writing your own inet_pton - and why would
you do that??

**Comment by mwpowellhtx** [comment]
@gdamore I've already presented my use case, but apparently was met with a brick wall. At this point I'm not hung up on it and am working around it.

**Comment by gdamore** [comment]
Actually, your use case was "htonl", and a stack overflow article that made no sense to me.  (Why would the post have an IPv6 address in the form claimed?  It's not normal application usage that's for sure.)  So what I'm trying to understand is why you have this need for 32-bit (or 16-bit or 64-bit) quantities?  How is it that you have IPv6 address(es) in this form, or conversely, what kind of API do you have that needs them in that form?  (I see Windows defines struct in6_addr as a union with an array of Bytes and Words...  no statement as to byte ordering there, but when that structure is carried as part of a sockaddr_in6 it *must* be in network byte order per IPv6 sockets.  (RFC 2553).

Note that RFC 2553 also defines

```
      struct in6_addr {
          uint8_t  s6_addr[16];      /* IPv6 address */
      };
```

(From that perspective winsock is not RFC conformant ... but that is hardly surprising.)

Btw, @SG7 anonymous unions are new in C11 (older in C++ I think).  Since we're constrained to C99 we cannot use them.

**Comment by gdamore** [comment]
Actually, looking at RFC 2553, it says a bit more:

```
   The structure in6_addr above is usually implemented with an embedded
   union with extra fields that force the desired alignment level in a
   manner similar to BSD implementations of "struct in_addr". Those
   additional implementation details are omitted here for simplicity.
```

This makes sense because *host* stacks want to use something more natural to them than byte arrays.  (Such as groupings of words, dwords, or quadwords.)  But applications should never be doing that.  Applications should only treat these as 16 bytes in network byte order.

**Comment by gdamore** [comment]
The example further shows "hiding" the details and using a #define to get past the union member:

```
   struct in6_addr {
        union {
            uint8_t  _S6_u8[16];
            uint32_t _S6_u32[4];
            uint64_t _S6_u64[2];
        } _S6_un;
   };
   #define s6_addr _S6_un._S6_u8
```

**Comment by mwpowellhtx** [comment]
I have to say the focus here is among the blades of grass, where as mine is on the field. Yes, I understand the conversion to/from network byte order. In my mind that is the assumption. I just need the fields that support it using the appropriate 2- and 4-byte conversions.

**Comment by gdamore** [comment]
The point I was trying to make is -- WHY ARE YOU CONVERTING THESE?

inet_pton and inet_ntop already give you the right ordering.  All other typical IPv6 APIs already operate on these in network byte order.

**Comment by mwpowellhtx** [comment]
Once again this is something I was unaware of re: *inet_pton/inet_ntop*.

**Comment by gdamore** [comment]
Those are the standard functions when dealing with IPv6.
