### ISSUE TITLE
Undefined reference to InterlockedAddNoFence (mingw64)

### ISSUE THREAD

**Issue by wormyrocks** [nanomsg/nng#1210]
## NNG & Platform details.
Latest clone from master, but has been occurring for a while.
win10 x64, mingw 8.1.0, POSIX threads / SEH

## Expected Behavior
Tests build properly

## Actual Behavior
Tests fail to build with error

## Steps to Reproduce
Clone from master, install [this](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download) mingw toolchain, and build tests with cmake.

CMake error message attached (from command `cmake.exe --build -G "MinGW Makefiles" --config Release &> cmake_build_output.txt`). Possibly has something to do with MinGW #defines not being properly set by cmake?
[cmake_build_output.txt](https://github.com/nanomsg/nng/files/4257218/cmake_build_output.txt)

**Comment by bbblitz** [comment]
Looks like this might be related to #868 , just copy/pasting the fix doesn't sit well with me though.

**Comment by gdamore** [comment]
Yeah, its probably the same problem, with the same fix.  Gawd I despise mingw64.

The problem is that it pretends to provide the Windows APIs, but it doesn't "really" do so.  And from what I can tell they don't update to add these missing ones.  So instead of mingw being just free compilers to build Windows, it is more like an entirely separately platform.  TBH, given that VSC is pretty much entirely free for anyone using it for non-professional work (and not that bad for professional users), I don't understand why anyone uses it.

(There are also other options available -- Clang and Intel C for example.)

**Comment by gdamore** [comment]
I'm not 100% certain the fix is right -- only about 99.9%.

Because I don't have an mingw64 setup, nor do I really want to bother with setting it all up.

Anyway, give the latest a whirl, and let me know if it doesn't solve this for you.
