### ISSUE TITLE
build nng with ndk in visual studio

### ISSUE THREAD

**Issue by foroughmajidi** [nanomsg/nng#1223]
I run vcvarsamd64_arm.bat in cmd.exe and
mkdir build && cd build
cmake -G"Visual Studio 16 2019" -A ARM -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release ..
and then I built it in visual studio
but when I use the dll and lib in visual studio android solution the dll and lib don't work
How can I build nng library with ndk in visual studio?
I need nng.so for android solution in visual studio
thanks

**Comment by foroughmajidi** [comment]
please tell me how I can  do it?

**Comment by gdamore** [comment]
I haven’t had time to investigate.  It should build like any other project with CMake.

**Comment by gdamore** [comment]
You've asked the same question, I think, in several other bugs.  I think you need to set up a toolchain configuration.

See: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

That provides pretty complete instructions.  Unfortunately, cross compilation is always a pain to set up.  It can be done, but working through it for each target OS can be annoying.

I'm going to close this bug, because its the same question already covered elsewhere I think, and I've provided a link to details.
