### ISSUE TITLE
framing error in SSL/TLS

### ISSUE THREAD

**Issue by zakharov** [nanomsg/nng#1235]
Cpp application is publishing camera images over wss. Message size is
about 300Kb. Nng version 1.2.6 worked fine. After upgrading to 1.3.0, the application keeps crashing. Debugging with mem sanitize suggests that the problem is here:
  
![image](https://user-images.githubusercontent.com/499052/79449833-34016880-7fe4-11ea-8e45-b317680d482c.png)

Test platform details:
Ubuntu 16.04,
gcc (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1) 7.4.0
mbedtls-2.16.6 compiled as shared library
nng tag 1.3.0 compiled with tls support as a shared library.

**Comment by gdamore** [comment]
Thanks.  I'd like to know the value of "nio" when this happens.  If you can see that, from gdb, it would be helpful.  (Probably something is giving more scatter/gather buffers than anticipated.  We reduced the permissible scatter gather list a lot in NNG 1.3 and I think this is probably why.)

**Comment by zakharov** [comment]
Indeed the problem is inside a while loop in the function **tls_tcp_send_start(tls_conn *conn)**.
nni_iov  iov array is fixed, it is set to [2];  If len is big enough, nio is > 1 and iov[nio].iov_buf is out of bounds.  
If I increase the size of nni_iov  iov to [20], my application does not crash anymore.

**Comment by gdamore** [comment]
So TLS attempts to limit transfers to 16K at a time.  It looks like the limitation here isn't correct, with the result that we wind up breaking a contiguous I/O into multiple iov entries.

**Comment by zakharov** [comment]
Yes, the problem is in the code below. iov array has fixed length of 2. Messages which are larger than 2*NNG_TLS_MAX_SEND_SIZE are causing segfault.

I guess iov should have a variable  length depending on the message size. Heap allocation could fix it, but maybe there are better ways. 
```
nni_iov  iov[2];
...
while (len > 0) {
		size_t cnt;
		if (tail < head) {
			cnt = head - tail;
		} else {
			cnt = NNG_TLS_MAX_SEND_SIZE - tail;
		}
		if (cnt > len) {
			cnt = len;
		}
		iov[nio].iov_buf = conn->tcp_send_buf + tail;
		iov[nio].iov_len = cnt;
		len -= cnt;
		tail += cnt;
		tail %= NNG_TLS_MAX_SEND_SIZE;
		nio++;
	}
```

**Comment by gdamore** [comment]
The issue is we need to do a partial transfer here -- we can send at most 16K at a time. Once that write() is completed, we can do another write() for another 16K.  I'll implement a test suite.  I do wonder if we should bump the limit up -- 16 K can be kind of small for certain workloads.  Although, most people are not going to be doing *lots* of giant transfers.

**Comment by gdamore** [comment]
So higher up in that function, at around line 1214 and 1225, we have code that should limit this.  The mystery is why we are trying to write more bytes than the space we have available.

**Comment by gdamore** [comment]
I'm going to work to debug this this weekend -- I'll write a test case.  The concern I have is that if you need more than two iovs, then you are wrapping, and probably corrupting data in the place.  Care was taken to try to ensure that this didn't occur, but I've obviously got a bug somewhere. 

Stay tuned.

**Comment by zakharov** [comment]
Great! I can debug my use case on Monday.

**Comment by gdamore** [comment]
I would like to see some reproducing code.  My attempt to reproduce this has failed, but it's possible I'm missing something here.  I will insert some assertions to help us catch this.

**Comment by gdamore** [comment]
I've created a test case for this in branch bug1235  -- I can't seem to reproduce your situation -- please have a look.

There are some minor changes which *could* address a problem, but honestly I'm having trouble seeing it.  One thing that is added to that branch is an assertion check, which should tell me if something is seriously wrong elsewhere.

Otherwise you might want to investigate your code -- possible heap overflows?

**Comment by gdamore** [comment]
I went ahead and merged that branch -- it's all good stuff and no reason to hold it back.

Please test and let me know if you're still having this problem.

If you have reproduction code to share, that would help.  (The smaller the program needed, and ideally a C program, the better!)

**Comment by gdamore** [comment]
You can also look in src/supplemental/tls/tls_test.c for the test case for this that seems to pass.

**Comment by zakharov** [comment]
Thanks! I still have the problem. I am working on the example to reproduce it.

Here is a debug output which I added in the tls_tcp_send_start:
nio: 2  conn->tcp_send_len: 16384  conn->tcp_send_head: 7664  conn->tcp_send_tail: 7821 

I also noticed that this problem occurs in the server when the clients are connecting/disconnecting.

**Comment by gdamore** [comment]
I guess you never triggered the assertion?

The send_len should never exceed 16384 -- because that's a limit we apply based on the buffer.

**Comment by zakharov** [comment]
I added a test scenario to reproduce the problem.  Here is the link: [https://github.com/zakharov/nng_tls_test](url)

The server is a publisher. The client spawn several threads with subscribers.
The server seems to crash either in 

**static void tls_tcp_send_start(tls_conn *conn)** 
or in 
**static int conn_handshake(nng_tls_engine_conn *ec)**

conn_handshake crashes if the nanosleep in the client code is commented.

Non of this happens when I am switching from wss to ws.

**Comment by zakharov** [comment]
Hello @gdamore. Are you able to reproduce the problem with my example?

**Comment by gdamore** [comment]
Sorry, I've been a bit sidetracked lately.  I should get to this this week.

**Comment by gdamore** [comment]
Something weird has happened.... because you have a send_len that is 16384 in that above, but your head and tail values suggest that you have a chunk at the end of 8563 (16384 - 7821) and a chunk at the beginning (wraparound) of 7664.  Adding those up there is a discrepancy -- 16227, so 157 extra stray bytes.

This concerns me greatly as it may indicate that the framing is corrupted somehow.  I'm looking more closely.

**Comment by gdamore** [comment]
So finally figured it out.  I was advancing the tail pointer too soon, such that if we failed to send as much as we asked for, this could lead to the tail being at the wrong place.

This is actually a message corrupting bug.  I'm glad to have nailed it, and very grateful for your test case.  I am going to refactor the test case into vanilla C so that I can include it in the test suite.

**Comment by gdamore** [comment]
Your test case might be hard to refactor since it depends on running for a while.  PR with the fix out though.
