### ISSUE TITLE
Timeout options should still be uint64_t

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#124]
What was it before? ``uint64_t``? It should still be, not ``int32_t``. That's causing issues in the unit conversion from microseconds.

```
2>G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\protocol\bus.cpp(86): warning C4244: 'argument': conversion from '__int64' to 'nng::duration_type', possible loss of data
2>G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\protocol\bus.cpp(87): warning C4244: 'argument': conversion from '__int64' to 'nng::duration_type', possible loss of data
2>G:\Source\Spikes\nanomsg\cppnngswig-working\swig\cpp\tests\protocol\bus.cpp(88): warning C4244: 'argument': conversion from '__int64' to 'nng::duration_type', possible loss of data
```

Thanks!

**Comment by gdamore** [comment]
Yes it was 64-bits. I switched to 32-bit signed types for relative times
(durations). With milliseconds thats enough to represent several weeks.

**Comment by mwpowellhtx** [comment]
I understand the units of measure. But changing the underlying supporting type is over zealous. I don't know what "for relative times (durations)" means.

The default type from Chrono is 64-bit unsigned. That worked perfectly before. No warnings. Post-change, now it is a scaling issue waiting to happen.

Please change the underpinning type back to 64-bit unsigned.

**Comment by gdamore** [comment]
So, std::chrono::duration is *not* specified to be 64-bit integers - that is entirely an implementation detail.  In fact, this could be floating points, or structural with high resolution and low resolution members as separate fields.  (E.g. an internal "seconds" and a "nanoseconds" field, ala struct timepsec -- in fact on Unix this probably a pretty common representation.)

std::chrono::milliseconds is supposed to return a templatized duration of int size >= 45 bits, so that they can cover the same width as int64_t as nsec (292 years).  There is no requirement that this be uint64_t though.  (But it probably almost always is.)

I believe all you need to do is add casts, because your durations should always be shorter than the several weeks that are supported with 32-bit values. (The idea that someone would set a timeout years in advance for a network protocol is kind of absurd.)

The other issue is dealing with -1 (infinite) and 0.  I don't believe that std::chrono::duration has any way to represent those values.

**Comment by mwpowellhtx** [comment]
I get that, you can specify the representation. From the stand point of ensuring proper duration unit casting, i.e. I was ("was" being the operative word) doing this:

```C++
#define CAST_DURATION_TO_MS(x) std::chrono::duration_cast<std::chrono::milliseconds>(x)
```

I don't have a *GCC* environment right in front of me, but the *VC 14.0* include defines it this way:

```C++
typedef duration<long long, milli> milliseconds;
```

Which isn't ``uint64_t``, either, I grant you, but it's a heck of a lot closer than ``int32_t``.

But it seems as though there is some sort of representational cast going on between, say, *100ms* (quantity arbitrary), which yields *100 std::milliseconds*, and the NNG want for 32-bit:

```C++
typedef ::nng_duration duration_rep_type;
typedef std::chrono::duration<duration_rep_type, std::milli> duration_type;
```

So I did a little work to add the *duration_type*-based get/set operations, which simply call into the named **_ms* operations.

That to say, let's run with it and see how it works for the time being (pun intended).

**Comment by gdamore** [comment]
Ok. I'm closing this for now then.
