### ISSUE TITLE
aio lifetime best practice?

### ISSUE THREAD

**Issue by GeeRez** [nanomsg/nng#1254]
What is the best practice for managing lifetime of an AIO?

I have set up Pair socket between two processes, connecting by TPC (expect IPC in future). They need async, arbitrary communication.

I have a struct with aio, msg and socket reference, representing a single message resources.

Discovered, same as this post: https://github.com/nanomsg/nng/issues/1249 Messages can't be trivially reused via clear & append.

Discovered, same as this post: https://github.com/nanomsg/nng/issues/1138 Messages can't be freed during the callback.

So currently buffering messages during callback and periodically freeing them from main thread.
This still causes read and write exceptions at that time, begging the question, how should we manage aio and message life time?

Trying NNG with current master source, also trying nngpp c++ wrapper, and building with MSVC 2017 on Windows.

**Comment by gdamore** [comment]
#1249 involved raw mode.  The best practice is to *not* use raw mode, but use contexts instead.  If you need raw mode, then you have to be careful about what you do with the headers.  This is not typical.

Bug #1138 is salient here.  What I generally recommend is to have one or more aios per "worker" object.   Ultimately what I really need to do is give callers a "deferred destroy" that lets them discard the aio asynchronously.  This would be easy to build on top of the nni_reap framework, I just need to do the work to do it.

In most applications, we use longer lifetimes for aios.  What I might do, for example, is have a pool of them representing workers.  This defines at some level  the concurrency of my application, but that's not unreasonable really since I don't want to be able to let a remote user submit e.g. millions of jobs and run my system out of resources.

So, using long lived aios is definitely recommended. :-)

**Comment by GeeRez** [comment]
Thank you very much for your response.

I am not familiar with contexts yet.  It appears I merely create one from a socket and use the context interface instead of socket thereafter. I'm not yet sure about lifetime or recycling of contexts. The demos don't quite follow the pattern I expect to use.

I did find a bug on my part with double freeing messages as the main cause of r/w exceptions. I must only free a message if the aio result was not success/zero.

I'm happy to close this issue, unless you're willing to comment further with any recommendations...
At the high level for sending, I want to 'fire and forget'  messages eg.
SendMessage("yellow");
SendMessage("red");
(Possibly some sends from different threads if safe.)
Internally I'm not sure how many contexts and aios I need. I had one socket to both send and receive, and one aio per message. I used the callback mostly to collect garbage on completed sends. The docs suggest I could create and share one context and repeatedly send aio with msg via nng_ctx_send(). (Rather than create ctx + aio + msg for every send.)
My apologies for ignorance, I've never used this or similar api before.

**Comment by gdamore** [comment]
You have the right idea about contexts.  You can create *many* contexts on a socket, and they share the socket and the underlying connections.

And yes, you should only a free message if it failed to send.  The reason we don't do that is that you might want to retry sending it.

If you're just using send/recv, with no state machinery, you don't need to use contexts at all.  Those come into play usually with stateful patterns like req/rep.

**Comment by gdamore** [comment]
Closing at submitters request.
