### ISSUE TITLE
IPv6 transport testing nni_plat_udp_open returning garbage return value

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#128]
Yet the UDP pointer is null, which leads me to believe the operation failed. This may be more likely a bridge that potentially gets traversed when UDP gets NNG exposure. For the time being I'll key on whether the pointer is valid, as well as the return value.

**Comment by gdamore** [comment]
You should not be testing that. It is an internal function.

**Comment by mwpowellhtx** [comment]
I am checking whether ``has_v6``, sir. How else do you propose I do that? You haven't exposed the interface (YET). So until you do, I will continue to do so.

**Comment by gdamore** [comment]
If it isnt exposed then it isnt meant for use.

**Comment by mwpowellhtx** [comment]
Yes, I get that. So my question re: ``has_v6`` stands.

**Comment by gdamore** [comment]
I see now that I'm looking at the code.  The test suite uses this to determine if the host is missing IPv6 support; the kernel might have it but some CIs do not configure a loopback in their containers.  If you're not using a CI, then you probably don't need this.

There are probably other ways to achieve this same test, but I'm using the UDP open, because it was readily available to me, and "portable", since I already will have the UDP stuff supported everywhere.

Another way would be to try doing "socket(AF_INET6, SOCK_DGRAM, 0);"  (might use SOCK_STREAM for an even more accurate test, since we're interested to know about TCPv6.)

You'd have to close the resulting SOCKET afterwards, and this might not be portable to systems without BSD sockets (some embedded systems), but you could just #ifdef wrap this and leave it at that -- it's unlikely that most of the tests would ever be useful in embedded environments.

**Comment by gdamore** [comment]
When you say "garbage" return value, what do you mean?  It may be that I'm returning an error code encoded with NN_ETRANSPORT (OR'ed with a GetLastError() value.)

**Comment by mwpowellhtx** [comment]
I'll check whether that's the case, thanks.

**Comment by mwpowellhtx** [comment]
Would you please expose that via NNG_ETRANSPORT? Thanks...

**Comment by gdamore** [comment]
Sorry, its NNG_ETRANERR, and already exposed.  There is also NNG_ESYSERR.  The NNG_ETRANERR is OR'd with an error code from a specific transport, to cope with errors coming from transports that don't map to a specific nng error code.  NNG_ESYSERR is the same, but for platform errors.

In general I try to avoid using these, but with some systems (Windows is terrible in this regard), the number of error codes is huge or even unbounded, so I don't have much choice.

nng_strerror() is supposed to provide printable output for these cases whenever possible, but that might or might not work (again depending on the platform).

Please supply the specific error code you are getting back, and I'll investigate further.  It's probably not "garbage", just an error code I haven't added in specific knowledge for.

**Comment by mwpowellhtx** [comment]
That was it. [System error 10093](http://msdn.microsoft.com/en-us/library/windows/desktop/ms740668.aspx). Well, if I may say so, definitely seems to be an API issue: *"Successful WSAStartup not yet performed."*

Such as it is, if I need to call something like *::nni_init*, fair enough.

**Comment by mwpowellhtx** [comment]
Apparently, calling the magic *::nng_init* did the trick. Runs perfectly!

```C++
void init(const std::string& addr) {
    REQUIRE(::nni_init() == 0);
    REQUIRE(nng::transport::has_v6() == true);
}
```
