### ISSUE TITLE
Single-threaded nng-based applications?

### ISSUE THREAD

**Issue by daniel-santos** [nanomsg/nng#1290]
Hello.  I'm new to 0MQ, nanomsg, and nng and I'm wondering what it would take to implement single-threaded applications with nng.  Maybe it's currently possible and I haven't discovered how yet?  My hope would be for an interface to shove my timers and file descriptors along with their callbacks to be polled / selected on in the nng "main" thread's loop.

I'm working on a little, single-core MIPS system and would like to keep context switches to a minimum when there's not a good reason to offload something to another thread or process.  I profiled it (with the thread marshaling) and still got 28k messages a second as-is, which isn't too bad, but I have a lot of other software on this board too.

Next year, we'll probably upgrade to a dual-core, double-ALU (two threads per core) MIPS µC, but we're single core/thread for now.

Thanks!

**Comment by gdamore** [comment]
You *can* implement a single threaded pattern in your app.  Have a look at nng_poll(), and or you can use poll()/select()/epoll() with the descriptors returned by NNG_OPT_SENDFD and NNG_OPT_RECVFD options.

However, behind the scenes, NNG still uses multiple threads.  That's unavoidable.

Legacy nanomsg and 0mq also use threads under the covers, but I believe in both cases there is only a single background threads, whereas NNG has a number of them.  If you're optimizing to minimize context switches as a first order problem, NNG might not be the best for your needs.

With NNG you will have one more context switch per message (because of the completion callback) than nanomsg or zeromq.  Most of the other threads will only run when dialing (to resolve DNS) or disposing of connections or sockets (a relatively rare operation, or at least it should be if performance is a concern).

Having said that, even on single threaded VMs, NNG performs reasonably well.  I don't know what your processing needs, but unless you need to process very high message counts, the extra context switches shouldn't be too bad.  (Having said that, I don't know what your system is.  Some systems have a much better threaded design than others.  Solaris and illumos is excellent.  macOS is pretty much crap.  Linux with glibc does pretty well.

**Comment by gdamore** [comment]
Btw, if you use a callback based approach, you will probably have better performance, because you will take fewer system calls than with nng_poll() or the those NNG_OPT_SENDFD and NNG_OPT_RECVFD.  (Or with zeromq or nanomsg.)  That's because we can service those with simple thread wakeups, and don't need to issue extra write or read system calls to integrate with your poll() system call. 

So probably optimizing away thread context switches will actually hurt performance elsewhere, probably in a worse way.

If you only need to be *truly* simple and single threaded (with just one thread doing nng_send/nng_recv calls, and not multiple outstanding calls, then that's not needed at all, and the extra system calls go away.  But only trivial applications can get away with such a simple design in my experience.

**Comment by daniel-santos** [comment]
My apologies, I forgot to click "Comment"!  Thank you for the response, this is very helpful.  I've been digging through nn_poll() and I see the handy little hooks I'll need.  Thank you!

**Comment by rowanzhu** [comment]
> nng_poll

I can't find nng_poll. I guess It should be nn_poll, right?
