### ISSUE TITLE
Error NNG_EAGAIN with push protocol when bulk sending messages from same thread

### ISSUE THREAD

**Issue by jk-cx** [nanomsg/nng#1324]
## NNG & Platform details.
latest nng from repo, Windows 10 64-bit, c++ and nngpp

## Expected Behavior
As a test, I'm **sending messages in bulk** from the same thread to a **push-pipe**. The calling code is an internal message queue (independent of nng) that has a message processing loop running in its own thread, so it's always the same thread that is pushing the message to nng. The system can push approximately 10 messages a millisecond this way. I'm sending batches of 10 messages for this test, each batch is initiated manually.

## Actual Behavior
In most cases, the first batch goes through no problem. The second batch starts dropping random messages, from batch 3 on the drop rate is around 50%. The messages are dropped with error **NNG_EAGAIN**.

The **errors disappear** and nng sends out even big batches without any problem if the **calling thread is put to sleep** before calling nng_sendmsg. Interestingly, yielding the thread ends up dropping less messages but it still happens. It doesn't seem to matter how long the thread is sleeping as long it's > 0. Also (without putting the thread to sleep) it seems that the drop rate is less on ws transport than inproc, but it's still dropping messages.

I've expected that nng's internal queue will be full at some point but 10 messages seems a little low. Also, once it starts dropping the messages it doesn't matter if there's seconds between the batches, the drop-rate stays high.

Is this expected behavior? Am I missing something? Any place that could be tweaked in order to avoid having to put the thread to sleep? 

## Steps to Reproduce
Difficult, this is in the middle of a project... I can try to create a simple c++ app to reproduce it if necessary but would like to avoid that if there's a simple gotcha :-)

**Comment by gdamore** [comment]
The first thing to be aware if is that there is indeed an internal buffer, and it is quite intentionally short.  This is so that we can get a good distribution when using multiple pipes -- you want to have backpressure feedback happen quickly in order to prevent sending a lot of messages down to a peer that might not get to them for a while, where another peer could accept the messages right away.

This is tunable.  There is a socket option, NNG_OPT_SENDBUF that specifies the count in messages of the send buffer.   You can make this as big as you like.  If you have only a single push socket, then I would suggest going ahead and making it big.

The second point is that I guess you must be using non-blocking sends.  That might not be ideal.  If you use the nng_send_aio() function with a callback, then you can actually run at optimum rate, but you do need to be able to pick the message for delivery from the aio callback.  It might be a fair bit of work to design for that, but I guarantee it will be faster than using poll() or whatever with non-blocking sends. 

The third point is that websocket has network buffering applied, whereas inproc does not.  The feedback from inproc is almost immediate.

Finally, I think the problem you may be encountering is doing too much work in a single thread, and that is not giving other threads (the background workers that deliver stuff) a chance to drain the queues, etc. 

Bumping the send queue size up is likely the simplest immediate resolution.  I'd recommend setting it at like 100 or 1000.  The cost to making it big is relatively low -- the queue only keeps pointers, so the queue itself won't consume much memory (though the queued messages themselves might consume a fair bit depending on their size.)

**Comment by jk-cx** [comment]
Oke... that clarifies a lot. I need to think about that for a while, how to fit that into our threading model.

One more question though: Is there a way to query how full the queue is? Not sure if that is a good idea but we could query how much backpressure there is in nng, if the queue is somewhere X% put the sending thread to sleep. That might work in our case because we have a upstream queue that can act as the buffer.

**Comment by gdamore** [comment]
Unfortunately, no, there is no visibility into the current queue depth.
I'm going to close this as I think I've given you several options.  If you're going to batch with non-blocking, which I specifically would advise against, you should just make sure that your queue depth is larger than your batch size... you will need some kind of feedback mechanism as well, so you stop doing bulk work if the queue is busy.

I actually would recommend, that if you're going to do this nonblocking bulk send, that you just accept that NNG_EAGAIN can happen, and return the message you were trying to send to the originating queue (i.e. save it for later).  This model is more or less just like attempting to write to a network socket with non-blocking write() -- you have to be prepared for EAGAIN to tell you can't write more data, and come back again later.

The better solution is to avoid ever getting those by not doing bulk processing at all, but by using aios and letting the callback thread retrieve a message from your message source, and then have it post it for send.   The alternative is to use blocking I/O with nng_aio_wait or an old style nng_send/nng_sendmsg, and do the work in a single synchronous thread (basically loop around retrieve message from source, send message to pipe).
