### ISSUE TITLE
Test nng.ws failed, "Incorrect URL paths do not work"

### ISSUE THREAD

**Issue by Fredo699** [nanomsg/nng#1332]
## NNG & Platform details.

nng 1.3.0 (latest from master)
platform: arm 32-bit am335x (beaglebone black) with Debian Buster, kernel version 4.14.108.

## Expected Behavior

All tests pass

## Actual Behavior

All tests pass, except nng.resolve (expected, because I don't have ipv6 set up), and nng.ws (unexpected).

I'm not sure what is happening here, or if this is even an issue for my use case or not, but I can't find anyone else with this problem, so I figured I should open an issue.

Running the test on its own with `-v` supplied yields the following:

```
=== RUN: WebSocket Transport

  Given transport ....
    Scheme is correct ......
    Connection refused works ........
    Duplicate listen rejected .........
    Listen and accept .........
    Send and recv ..........................
    Send and recv large data .......................
    Send and recv multi ............................................................................................................................................................................................
    Properties test ............................................
  Empty hostname works ....
  Wild card hostname works ....
  Incorrect URL paths do not work ...X
  Double wildcard listen works .....
  Wild card port works and can be used again ......


Failures:

  * Assertion Failed (Incorrect URL paths do not work)
  File: ../tests/ws.c
  Line: 84
  Test: nng_dial(s2, addr, ((void *)0), 0) == NNG_ECONNREFUSED



340 assertions thus far

--- FAIL: WebSocket Transport (2.13s)
FAIL
FAIL    ./ws                                                   2.143s
```

## Steps to Reproduce

* Clone latest from master
* Build w/ ninja
* Run `ninja test`

**Comment by gdamore** [comment]
This test fails from time to time in CI/CD.  I think the problem is that it is fragile in the face of other users of TCP ports.  Refactoring the tests to be less brittle in this regard is definitely on the list of things to do.  I don't think this represents a problem with NNG itself, just with the test suite.

**Comment by Fredo699** [comment]
@gdamore Thanks for the quick response.

Could you explain what exactly is being tested here? I'm not sure I understand why "incorrect URLs" would be expected to work in the first place.

**Comment by gdamore** [comment]
It's a negative test.  What it's trying to do is verify that if the server does not support the given path URI, that it results in a 404 error, and that error is turned into NNG_ECONNREFUSED by the NNG websocket framework.

The test may be brittle in environments where v6 and v4 resolution of INADDR_ANY doesn't work.  I bet if I put in a 127.0.0.1 instead of name based address, it would Just Work.
