### ISSUE TITLE
poor performance for req/rep mode

### ISSUE THREAD

**Issue by shishaotang** [nanomsg/nng#1362]
**Is your feature request related to a problem? Please describe.**
hello, I use nng req/rep mode for some reliable transfer, I want to know the performance, so I write test code just like this:
req side:
	nng_socket socket;
	nng_req0_open(&socket);
	int ret = nng_dial(socket, addr_bus, NULL, 0);
	if (ret)
	{
		STLOG_ERROR << "dial failed " << nng_strerror(ret);
	}
	nng_msleep(3 * 1000);
	STLOG_INFO << "begin send ";
	for (int i = 0; i < 100000; ++i)
	{
		nng_msg* msg_sended;
		nng_msg_alloc(&msg_sended, 0);
		nng_msg_append(msg_sended, reqstring.c_str(), reqstring.length());
		nng_aio* aio;
		nng_aio_alloc(&aio, NULL, NULL);
		ret = nng_sendmsg(socket, msg_sended, 0);
		if (ret)
		{
			STLOG_ERROR << "send failed " << nng_strerror(ret);
		}
			//send and wait for response
		nng_msg *recv_msg;
		ret = nng_recvmsg(socket, &recv_msg, 0);
		if (ret)
		{
			//todo error log
			STLOG_ERROR << "recv failed " << nng_strerror(ret);
		}
		nng_aio_free(aio);
	}
	STLOG_INFO << "end send ";

and response side:
	while (true)
	{
		nng_msg* msg;
		int nret = nng_recvmsg(response, &msg, 0);
		if (nret)
		{
			STLOG_ERROR << "nng bus recv failed, nRet = " << nret << " " << nng_strerror(nret);
		}
		else
		{
			nng_msg *msg1;
			nng_msg_alloc(&msg1, 0);
			std::string sendmsg = "request/response use context test, msg number is ";
			nng_msg_append(msg1, sendmsg.c_str(), sendmsg.length());
			int nret = nng_sendmsg(response, msg1, 0);
			if (nret)
			{
				STLOG_ERROR << "send msg error " << nng_strerror(nret);
			}
		}
	}

and the request side log 
## 2020-11-30 13:06:17.604725 (0x000053d8) [info_] [...request.cpp:138, int __cdecl main(void)]: end send 
send 100,000 pieces data used 8 second
almost 12124 pieces data per second，I want to know is this the real performance？ or something wrong I used nnglib in my code？
my test machine is win10 64bit，intel i7-10710U 1.1GHz
thank you very much！

**Comment by gdamore** [comment]
So your test methodology is busted.

Basically you are testing not how many requests per/second that NNG can do, but how fast a single NNG client and server can exchange requests.  This brings into play many factors that have nothing to do with NNG, most notably the time it takes (latency) to get a single message through the TCP/IP stack (I'm assuming you're using TCP/IP.)  This test also fails to engage much in the way of multiple cores on your system because it's inherently single threaded.

12k/sec is actually not terrible given this.  But NNG can process many many more.  You should have multiple clients moving data, and calculate the aggregate.  It is possible on some systems to get to 1M/sec, but that might not be the case with only a 1.1GHz CPU -- this particular CPU is considered a "mobile" CPU so you're probably likely to get quite a bit less.  But still, its pretty easy for me to imagine that you might get something like 6-10x your number simply using parallelization.   You might find that depending on much time your CPU is idle, you can get significantly more than that.

Also, you're not using aio structures, so you can save a little of CPU (and memory) by not allocating or freeing them.  (Your code allocates one each request, and this comes at a cost.)  It would not surprise me if you find you can get several percent better numbers by eliminating that waste.

You might also find you get better numbers with larger messages if you allocate larger messages  (message sizes) initially, truncate them, and only append afterwards.  This avoids realloc which is also not free.

**Comment by shishaotang** [comment]
Thank you for your feedback. I used IPC proto for this test， and  I want to use req/rep mode for a reliable transfer in a financial system.  This system receive an ordered flow and transfer to another process by ipc or tcp，so if I use multi thread to send this ordered flow， the flow will become unordered in the receive side.  I will try your method by using aio structures and allocate larger messages， thank you very much.

**Comment by gdamore** [comment]
Right. ... if you're using ordered flows you're going to do fewer messages per second, because of the implicit serialization.  I've processed 1M+ per second on reasonable server hardware, but you need to recognize that you have to account for two round trips with REQ / REP.  This worsens the situation for latency unfortunately.

Note that ordering of REQ/REP processing is not guaranteed if you post multiple messages -- you need to have only one message outstanding at a time to ensure ordering.
