### ISSUE TITLE
Make core/list.h and core/reap.h public

### ISSUE THREAD

**Issue by ev-ermakov** [nanomsg/nng#1364]
Hello! Please consider making this public:

 - `nni_reap_item`, `nni_reap()`
 - `nni_list`, `nni_list_item`, `nni_list_*()`

So one doesn't need to reinvent the wheel each time.

**Comment by gdamore** [comment]
nni_reap() is likely to remain private for the foreseeable future.  Its an internal utility for deferred destruction of objects.  I don't think I want to make this public, since at that time I have to promise to support it in basically the same manner ~forever.  Keeping it private lets me evolve this however I want without worrying about breaking user programs.

The reason that nni_list APIs are private is that I considered them an implementation detail, and have been hesitant to go down the road of trying to make NNG a general purpose programming library.  Having said that, with the nng streams APIs, and HTTP, we may be past that point.   There are also some other utility functions in nng that are intended to ease writing portable programs (nng_sleep, etc.) so maybe this is just another of those.

What I would not like to happen at this point is for folks to start asking for other utility functions to be created -- more string manipulation, data structures (binary or AVL trees, trie objects, etc.)  Once that happens we can easily lose the focus of NNG which is to provide friendly interfaces for building distributed programs.  Originally it was even more focused since it was just about the SP protocols, but already we're looking at shifting away from that.
