### ISSUE TITLE
panic: nng is not fork-reentrant safe

### ISSUE THREAD

**Issue by zg9uagfv** [nanomsg/nng#1373]
**Describe the bug**
fork()

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - lastest
 - ubuntu20.04
 - c++
 - static library

**Additional context**

`
panic: nng is not fork-reentrant safe
This message is indicative of a BUG.
Report this at https://github.com/nanomsg/nng/issues
./HsCentralService() [0x4375bc]
./HsCentralService() [0x440f64]
./HsCentralService() [0x43436c]
./HsCentralService() [0x42fe18]
./HsCentralService() [0x42c7dc]
./HsCentralService() [0x42c684]
./HsCentralService() [0x40bf04]
./HsCentralService() [0x407bf8]
./HsCentralService() [0x42b5c0]
/lib64/libc.so.6(__libc_start_main+0xe0) [0x7f889ada60]
./HsCentralService() [0x404bcc]`

**Comment by gdamore** [comment]
Yep... You cannot use fork() with NNG (although you can use fork() if you immediately follow it up with exec().)

Basically, it's close to impossible to correctly support threading in the face of fork().  (The issue is that the state of mutexes is indeterminate.  In theory pthread_atfork() was meant to fix this, but it turns out that restrictions on what you can call from those handlers means that even this is unsupported.)

You *can* fork before the first call any NNG library function.  But after NNG initializes, any further use of an NNG API in the child is verboten.
