### ISSUE TITLE
Message body/header 32-bit unsigned int endianness

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#141]
I need to know, how are you treating the byte order of the 32-bit unsigned int? What's the endianness?

For instance, when I append 1, that appears to be big endian, literally, {0,0,0,1}, whereas I am expecting {1,0,0,0}.

Are you making any assumptions about network or host byte order?

**Comment by mwpowellhtx** [comment]
Why in the world do you [reverse the bytes](http://github.com/nanomsg/nng/blob/4e668fdd5b5da0d46f97d835249dbe5f0ea319a7/src/core/defs.h#L93)? Why not just drop them in as-is?

```C
#define NNI_PUT32(ptr, u)                                    \
	do {                                                 \
		(ptr)[0] = (uint8_t)(((uint32_t)(u)) >> 24); \
		(ptr)[1] = (uint8_t)(((uint32_t)(u)) >> 16); \
		(ptr)[2] = (uint8_t)(((uint32_t)(u)) >> 8);  \
		(ptr)[3] = (uint8_t)((uint32_t)(u));         \
	} while (0)
```

I contend that I should be able to do a simple byte for byte comparison of the gotten ***void**** buffer and the *expected integer value* and they agree, without going through reverse machinations.

**Comment by gdamore** [comment]
Your expectations would be incorrect.

The specifications state that, like most network protocols, the order of bytes on the wire is generally in what is termed "network byte order" -- that is big-endian.  (This is true for the headers, the user payload is unmolested.)

It is vital that all participants agree about the byte order of fields placed on the wire -- and processors can disagree about this.  (These days almost all CPUs are little-endian, but the big-endian ordering is firmly rooted in history.  Early CPUs were more often big endian, and big-endian examples still exist -- SPARC for one.) 

At any rate, the byte order was chosen by Martin in nanomsg legacy, and in order to preserve wire compatibility we have to use the same byte ordering.

Again, user payloads are not subject to this -- and users are responsible for dealing with any endianness issues in their own protocols.

**Comment by gdamore** [comment]
You should not be using or accessing either the NNI_PUTxxx or NNI_GETxxx macros, nor any data region (headers) that they affect -- modulo *raw* mode headers.

**Comment by mwpowellhtx** [comment]
Thanks for the clarification. :+1:

**Comment by mwpowellhtx** [comment]
Why would I access internals here? I am verifying using the external API, literally getting the buffer back and verifying that against the 32-bit integers.
