### ISSUE TITLE
pair.c compiler warning

### ISSUE THREAD

**Issue by unspecd** [nanomsg/nng#1415]
```
src/sp/protocol/pair1/pair.c:418:3: warning: 'l' may be used uninitialized in this function [-Wmaybe-uninitialized]
```
Not sure if it matters, though.

**Comment by unspecd** [comment]
One more warning:
```
src/testing/marry.c:228:13: warning: 'colon' may be used uninitialized in this function [-Wmaybe-uninitialized]
```

**Comment by gdamore** [comment]
The first one is kind of a compiler confusion.  l can't be  used uninitialized because we look for a to not be NULL, which only happens in if branches that set l.  Basically the analyzer is not sufficiently smart.  I'll explicitly initialize l though to shut it up.

The marry warning is actually a real bug.   But probably not actually harmful (its only test code, and those cases always pass a string that won't trigger undefined behavior.)  I'll fix that too.
