### ISSUE TITLE
Build failure of posix_pipe.c when using older gcc

### ISSUE THREAD

**Issue by minyang** [nanomsg/nng#1448]
**Describe the bug**
When building nng with an older gcc (4.3.2), build fails due to `#pragma GCC diagnostic` directive being inside:
```
/home/proj/nng/1.4.0/source/src/platform/posix/posix_pipe.c: In function 'nni_plat_pipe_raise':
/home/proj/nng/1.4.0/source/src/platform/posix/posix_pipe.c:106: error: #pragma GCC diagnostic not allowed inside functions
/home/proj/nng/1.4.0/source/src/platform/posix/posix_pipe.c:107: error: #pragma GCC diagnostic not allowed inside functions
/home/proj/nng/1.4.0/source/src/platform/posix/posix_pipe.c:109: error: #pragma GCC diagnostic not allowed inside functions
CMakeFiles/nng.dir/build.make:576: recipe for target 'CMakeFiles/nng.dir/src/platform/posix/posix_pipe.c.o' failed
make[3]: *** [CMakeFiles/nng.dir/src/platform/posix/posix_pipe.c.o] Error 1
```

**Expected behavior**
Build succeeds.

**Actual Behavior**
Build failed.

**To Reproduce**
Build nng v1.4.0 with gcc 4.3.2

**Environment Details**
 - NNG version: v1.4.0
 - Operating system and version: Ubuntu 16.04 LTS
 - Compiler and language used: GCC 4.3.2
 - Shared or static library: static (libnng.a; default)

**Additional context**
I understand this particular gcc is way outdated and may not justify effort to fix this issue.  For my use case, I have to maintain older version of SW.  It is totally fine if this issue is determined as WON'T FIX, but would appreciate if this issue could be handled.
Looks like this is a known issue with older GCCs (e.g., [link](https://stackoverflow.com/questions/16555585/why-pragma-gcc-diagnostic-push-pop-warning-in-gcc-c)).

**Comment by gdamore** [comment]
This is a no-win scenario.  Ancient GCC doesn't like the pragmas and barfs.  But modern GCC complains if we don't do this.  (The issue is that I really do want to ignore the return result from the write to the pipe. Some "helpful" person decided to annotate the system headers so that a warning is generated when this result is ignored -- but again, sometimes ignoring the result is perfectly reasonable, as in this case.

You can safely remove the pragmas in your local fork.

It might be possible to use an #ifdef  to guard them.  I have no idea when GCC introduced this pragma.

**Comment by minyang** [comment]
@gdamore Thank you for quick response.  Yes, I already forked the repo and created a branch where I commented those pragmas out.  Glad to confirm with you that it is safe to remove them.  Other than that, all worked well out of the box.

A few years back, I've used nanomsg for production and really liked it.  So I wanted to give it a shot again for upcoming projects and realized nng is the way to go.  Looking forward to getting my hands on it!
