### ISSUE TITLE
There's NO method to check whether a listenning socket has connected?

### ISSUE THREAD

**Issue by leonleeann** [nanomsg/nng#1494]
Sorry for posting my question here!
This is my first time to use NNG. I don't know whether there is a offical/populated supporting forum of it, so I ask my question here. If such a forum exists, pls tell me. Thanks!

**Background:**

- I'm implementing a pair of long time background services, those are communicating with NNG;
- Protocol: pair0 @ tcp;
- The payload message occurs maybe a second, or maybe a day;

**My question:**

1. Does NNG automaticlly transmit a "Heartbeat" msg peroidly to each peer to keep the TCP connection alive, if there is no producing msg for a specific time duration? If NOT, should I do "HeartBeat" by myself?
2. Can I use **async** mode to receive and **sync** mode to send with a same pair0 socket?
3. How to check the status of a socket, such as "listenning/connected/disconnected"?

Pls forgive my poor English.

**Comment by PHLF** [comment]
### YES

1. https://nng.nanomsg.org/man/v1.3.2/nng_tcp_options.5.html
2. You should be able to do it (need confirmation)
3. https://nng.nanomsg.org/man/v1.3.2/nng_pipe_notify.3.html

Hope that helps ;)

**Comment by gdamore** [comment]
Thanks @PHLF .  

1.  TCP does offer a keepalive, via the options.  However, if you need to verify end-to-end connectivity (for example to make sure your application is alive) you should make your own heartbeat message.  This is required if you use nng_device (since the keepalive is only local to the TCP channel and not proxied over the device), and it will also help you detect a case where the TCP connection is still up but the remote application is non-responsive.
2. Yes, you can mix and match sync and async freely, although I recommend only having a single outstanding operation per direction at a time.  (Technically with pair protocol this isn't a restriction, but other protocols have state machines that will limit this, and it can be confusing to manage many pending operations against the same socket.)
3. "Sockets" don't have a connected state, instead they have pipes (although pair0 can only support a single pipe at a time), and you have to use the nng_pipe_notify() API at present.  I'd be willing to create a socket option which returned the number of connected pipes, but I'd be opposed to adding complexity to get the pipe details from the socket directly.  That way is likely to be problematic at best, and is kind of an application anti-pattern anyway.
