### ISSUE TITLE
local_address

### ISSUE THREAD

**Issue by jinyuttt** [nanomsg/nng#1501]
address：tcp://*:0;
Call NNG_ listener_ get_ Addr gets the port. The client connection fails. It feels that the obtained address is incorrect.

code:
lissock = nng::rep::open();
		try
		{
			lissock.listen(url.c_str());
		}
		catch (nng::exception e)
		{
			std::cout << e.what() << std::endl;
		}
		catch (const std::exception&e)
		{
			std::cout << e.what() << std::endl;
		}
		
		nng::listener lis(lissock, url.c_str());

auto addr = lis.get_opt_addr(nng::to_name(nng::option::local_address));
switch (addr.s_family)
				{
				case   nng_sockaddr_family::NNG_AF_INET:
					port = addr.s_in.sa_port;
						inttoIp(addr.s_in.sa_addr, ip);
						break;
				case nng_sockaddr_family::NNG_AF_INET6:
					port = addr.s_in6.sa_port;
					ipv6_to_str(ip, addr.s_in6.sa_addr);
					break;
				case nng_sockaddr_family::NNG_AF_UNSPEC:
					port = addr.s_in.sa_port;
					inttoIp(addr.s_in.sa_addr, ip);
					break;
				default:
					break;
				}

**Comment by jinyuttt** [comment]
The acquired port has always been 52428

**Comment by gdamore** [comment]
Its likely that you're accessing an incorrect part of the structure -- the value 52428 corresponds to 0xCCCC -- which is a palindrome when considered as a byte sequence.

I'm not to familiar with "modern" C++ so I'm wondering if something is going on here that I am not seeing.

The value for "port" should be reasonable, but something isn't right. 

One thing you can do is look at the test code for this - test_tcp_port_zero_bind() execute this (but it uses 127.0.0.1 rather than the wild card for INADDR_ANY).

You might also try obtaining a different property:

NNG_OPT_TCP_BOUND_PORT

This property gives you the TCP port that you just bound to, directly.  It also presents it in native endian order.

NNG_OPT_URL

This property should give you the URL you can use to connect to the listener, and will replace the wild card port number.  (It won't resolve your wild card IP address though.

**Comment by jinyuttt** [comment]
It is found that I have a problem with the binding method.

thanks.
