### ISSUE TITLE
DLL integration not re-entrant, not thread-safe

### ISSUE THREAD

**Issue by mwpowellhtx** [nanomsg/nng#153]
I am well beyond *"the C code"*. Rather, my starting point is the C calling conventions exposed via the *DLL*, whose calling context is *threaded* when multiple test fixtures being run. These can be homogeneous or heterogeneous protocols/transports. Does not matter.

I've documented this is [not an addressing thing](151#issuecomment-341939957). Furthermore, I don't but this has anything whatsoever to do with *"IPC"*. I even ran using [IPv4 test cases](151#issuecomment-342245604) in order demonstrate that scenario.

Best guess, your code must be re-entrant in order to be considered thread safe. So far, I see no evidence that it is.

See [issue](151) for background.

**Comment by gdamore** [comment]
I'm not even sure what this is, beyond an attempt to waste my time.  You're guessing, and not writing any C code which demonstrates any actual bugs.  I have no interest debugging your environment, as I have stated ad naseum.

Please  cease and desist.

**Comment by gdamore** [comment]
Just a bit of a warning as well, @mwpowellhtx -- if you continue to try to force the issue and refuse to collaborate in the manner that I've requested for nng (specifically if you are going to submit bugs, please include a reproducible test case *in C*), then my next step will probably be to block you from the github nanomsg org altogether.

Obviously I consider that a rather drastic measure, and one to which I would prefer not to have to resort.   But as a measure of self-defense for the project, if I have to take that step I will.

The way to avoid this occurring is rather simple -- if you'e going to submit bugs against the project, please do so in the manner I've requested.  In particular, continuing to try to reopen the same issue because you're not satisfied with my response, and are unwilling to even *attempt* to provide me the useful information I've requested, is a sure fire way to see the ban engaged.

**Comment by gdamore** [comment]
This also records for posterity that I've suggested that @mwpowellhtx simply step away from the nng derived/based projects for the time being.  At this time I don't think nng is mature enough to sustain collaboration with folks who are not willing to engage in whitebox analysis and constructive collaboration.  There are still sharp edges in this project, which is pre-release.
