### ISSUE TITLE
bug in initialization of dialer or listener

### ISSUE THREAD

**Issue by wutianze** [nanomsg/nng#1534]
**Describe the bug**
1. 
Spelling mistake in src/core/socket.c line 1084:
#ifndef NNG_ELIDE_DEPRCATED
should be
#ifndef NNG_ELIDE_DEPRECATED
which will make this block of code be run all the time.

2.
src/core/socket.c line 597-605:
When setting the default value of option nodelay and keepalive of dialer and listener in nni_sock_create, the dialer or listener list in the sock is empty, so the setting option seems to be meaningless. However, when creating a dialer or listener(ex. in posix_tcpdial.c), the default value of nodelay or keepalive is not set.

**Comment by gdamore** [comment]
The elide deprecated bug is fixed now (thanks for the report), so I'm converting this bug to track just the second issue.

**Comment by gdamore** [comment]
I believe that those options should only be transferred or set on the socket if using legacy mode.  As they are end point specific, modern applications should just set them directly on the endpoint.

**Comment by wutianze** [comment]
> I believe that those options should only be transferred or set on the socket if using legacy mode. As they are end point specific, modern applications should just set them directly on the endpoint.

Yes, I agree. The only problem is that when I create a dialer or listener by default, the code in nni_sock_create lets me believe the tcpnodelay option of the socket is opened. However, in fact, the option value is false. Hopefully, those who really care about this should set options explicitly, so it is not a problem.

**Comment by gdamore** [comment]
It's still a bug, so keeping it open.  At least in legacy mode it should behave correctly, and right now it does not.

**Comment by gdamore** [comment]
So I don't think there is actually a bug here.  I just went back through the code, and I think you may be assuming that this doesn't work, but you've missed some code.

*Assuming* that you have not elided deprecated options, the options get set on the socket.  When the dialer or listener is ultimately added to the socket (not in the platform specific, but in (for example) nni_sock_add_dialer(), we will replay those options down to the dialer from the socket.  (This works the same for listeners too.)

I suspect you're just assuming a certain order of operations that don't match the current implementation.

Please *test* this, and if you find otherwise, reopen this bug (or open a new one) with that information.
