### ISSUE TITLE
Configure pair protocol not to drop messages?

### ISSUE THREAD

**Issue by bucurb** [nanomsg/nng#1539]
Is there a way to configure the pair0 protocol on top of ipc:// to guarantee no messages are ever lost? Additionally is there an ordering guarantee - or is there a way to configure pair0 to guarantee messages are delivered in the same order?

**Comment by janjaapbos** [comment]
There is no configuration option for guaranteed delivery. This is something that the application could implement on top of pair.

To my knowledge, messages are sent in order of creation, but there is no guarantee that they are received in order. There is also no check on the receiving end of the order. Again this could be built on op of pair in the application.

REQ/REP does provided these guarantees, but it has the limit of a single flow direction and added latency due to acknowledgement of receipt of each message.

**Comment by gdamore** [comment]
Generally speaking if you aren't using a device in the middle, once connected two pair members will not reorder messages nor drop them.  This is only the case for pair0 and normal (not polyamorous) pair1.

More specifically pair uses flow control to avoid dropping messages.  Instead back pressure is applied.

Of course if the connection is lost then so may be any partially delivered messages.

**Comment by gdamore** [comment]
I'm closing this as its not an issue.
