### ISSUE TITLE
About making sock_init void function instead of int

### ISSUE THREAD

**Issue by wutianze** [nanomsg/nng#1559]
I noticed that the sock_init function no longer returning int after the commit `Socket and context initialization never fails.`. However, maybe it's not a good idea. 

This means it's impossible to add some new elements whose initializations may fail to the sock (for me is the case, I implemented a new protocol that has some message queues inside the sock, I cannot figure out a solution to initialize my sock elegantly without using lmq instead). Since `nni_sock_create` still returns an error, it is not bothering to forward the return value for sock_init. 

Thanks.

**Comment by gdamore** [comment]
I think it would be worthwhile to consider making a version the msg queue that doesn't fail initialization.  

But I'm also moving towards obsoleting the older msg queue stuff. It's quite a lot more complex and a lot slower than the lmq stuff.

**Comment by wutianze** [comment]
> I think it would be worthwhile to consider making a version the msg queue that doesn't fail initialization.
> 
> But I'm also moving towards obsoleting the older msg queue stuff. It's quite a lot more complex and a lot slower than the lmq stuff.

I think the reason why msg queue a lot more complex and a lot slower than lmq is because the msg queue does some work that is implemented in sock when using lmq. For instance, the msg queue deals with aio but lmq deals with msg directly(aio will bring the overhead when doing aio_finish and queuing of aio). Msg queue will queue aio first no matter what, but lmq can transfer the msg immediately in sock_send or sock_recv without queuing the aio when it is able to do that.

In fact, the msg queue is rarely used. I only find it in pair1-poly(not recommended to use) and some raw implementations. By the way, the raw mode seems to offload most work to users. So my advice is 1. just keep lmq implementation and leave most work for protocol, but give lmq its own mtx instead of the sock's 2.  make raw mode a new protocol instead of providing raw mode for every protocol, I do not quite find the difference between raw mode of different protocols. And the msg queue is mainly used in raw mode, by making them a one, we can deal with it better.

**Comment by gdamore** [comment]
Not every raw mode is identical, and there are some rather important differences in some of them.  (E.g. backtraces for REQ/REP, etc.)

The msgqueue implementation generally involves at least one more context switch.  The code for lmq can be a bit more optimized.  I've done some rather extensive benchmarking to prove this.  The main benefits are when the lmq can finish certain operations "synchronously".

I'm slowly converting protocols to use lmq instead of msgqueue.  Up until about 5 minutes ago, bus protocol used msgqueue as well.  But now it uses lmq.

I don't recommend anyone building new code use msgqueue -- the msgqueue implementation is *not* part of any public API, and I will almost certainly just remove before too much more time passes.

**Comment by gdamore** [comment]
I'm closing this -- I don't think I'll go back to making this function fail-able.  I'm trying to eliminate possible points of failure, and ultimately I'm also moving a lot of SP specific work out of the generic socket layer anyway.  The current implementations have reasonable ways to perform lazy initialization which is a bit more resilient as well.
