### ISSUE TITLE
retrieve local addr from listener

### ISSUE THREAD

**Issue by janjaapbos** [nanomsg/nng#1566]
When trying to retrieve the configured port for a tcp listener, a socket address with a correct IP but random port number is returned.

```
nng_sockaddr la;
size_t   z;
nng_listener_getopt(listener, NNG_OPT_LOCADDR, &la, &z);
```

la.s_in.sa_port is a random number, and not the actual port to which the listener is bound.

I want to retrieve the configured port for a listener, when the listener is configured with a url like "tcp://127.0.0.1:0".

**Comment by gdamore** [comment]
If using 0 specifically then no port is selected until one is bound.  And that port is chosen at random. And is what is returned.  This is so that you can use that port to connect to a peer. 

Put another way port 0 is magical. 

Configure a listener with a non-zero port and it will work more like you expect.

**Comment by janjaapbos** [comment]
Thank you. Could it be that I am mixing up host / network byte order for the port number? I will test further.

**Comment by janjaapbos** [comment]
Yes, I was looking at the wrong byte order. When converting the value with ntohs it is the value I expect.
