### ISSUE TITLE
Limits (restrictions) for PUB/SUB protocol

### ISSUE THREAD

**Issue by polovik** [nanomsg/nng#1627]
Are there presence some limits(restrictions) for PUB/SUB protocol:

- I.e. are number of subscribers for one publisher limited?

- Are number of topics for one publisher limited?

Could you please describe briefly – how implemented message delivery for any topic when there are many subscribers (in different applications) and they are communicate with PUB over Unix domain socket? I've thought that a publisher send multiple copies of one message, then each subscriber tries to peek new message, and if it has been already read - skip it. But seems logic is more complicated.

This information is needed because i'm plan to use many applications (> 20) which may subscribe to many topics from ONE major application (which acts as publicator).

Thank you! NNG is great!

**Comment by gdamore** [comment]
There are no builtin limits.  But as you scale, you might find that there are some "practical" limits on the number of *topics*, as the subscriptions are maintained in the subscriber as a simple linked list, and it does a memcmp() for each topic.  This is an area where we could probably do better for scaling.

So if you have a lot of messages with different topics that few clients care about, clients will spend a lot of time failing to match, so that's wasteful of bandwidth.

And if you have a lot of different subscriptions for a single client, it's going to be doing a lot of subscription matching, which also gets expensive.  (As a hint, if you have some topics that post a lot more frequently than others I think it will work better if you subscribe to them first, so they are matched first.)

As to the number of subscribers to a publisher -- you're only limited by the resources of the machine -- how many open files and if using TCP how many ephemeral TCP ports you have available.  Of course, as you're doing network traffic for each of those, you need to have enough CPU power to service them, but using nng_device() you can insert proxies and this can scale to millions of subscribers.  (Not that I've ever been able to confirm that ! :-)
