### ISSUE TITLE
How to specific tcp req local port number

### ISSUE THREAD

**Issue by rty813** [nanomsg/nng#1629]
How to specific tcp req local port number?
Or 
Can I set the random local port range?

**Comment by gdamore** [comment]
You can allocate a listener, and then set the NNG_OPT_LOCADDR on it.  That can specify a complete address -- including the TCP port number.

**Comment by rty813** [comment]
I want to specify dialer's port, should I set NNG_OPT_LOCADDR on **listener**?

**Comment by rty813** [comment]
In reqrep demo, I call `nng_dialer_get_addr` in client's every loop, but the sa_addr and sa_port different from every call. Is this OK?
```c
while (1) {

  printf("CLIENT: SENDING DATE REQUEST\n");
  if ((rv = nng_send(sock, cmd, sizeof(cmd), 0)) != 0) {
	  fatal("nng_send", rv);
  }
  if ((rv = nng_recv(sock, &buf, &sz, NNG_FLAG_ALLOC)) != 0) {
	  fatal("nng_recv", rv);
  }
  
  if (sz == sizeof(uint64_t)) {
	  uint64_t now;
	  GET64(buf, now);
	  printf("CLIENT: RECEIVED DATE: ");
	  showdate((time_t) now);
  } else {
	  printf("CLIENT: GOT WRONG SIZE!\n");
  }
  nng_msleep(sleep);
  sleep++;
  if (sleep == 4) {
	  sleep = 4000;
  }
        nng_sockaddr addr;
        nng_dialer_get_addr(dialer, NNG_OPT_LOCADDR, &addr);
        printf("%d, %d\n", addr.s_in.sa_port, addr.s_in.sa_addr);
  }
```

![image](https://user-images.githubusercontent.com/22488813/200099380-8bd74f9f-e9b8-44de-ba48-4e8f1c20ca34.png)

**Comment by rty813** [comment]
@gdamore any suggestion ?

**Comment by gdamore** [comment]
The documentation should indicate properly that the option for NNG_OPT_LOCADDR is an nng_sockaddr.   However, be advised that the port numbers are in network byte order, not host byte order.   For sa_addr, you're looking at the network byte order IP v4 address - so:

126.153.163.136

This is standard BSD socket practice.

When you call dial, by default you'll get a unique local address -- because that's the way TCP works.  You can *request* a specific source address, but that requires you set that option on the dialer.  Note that doing so will impair automatic redialing if the connection is lost, and will prevent being able to establish multiple outbound connections so I  don't recommend it unless you have no choice *and* you know exactly what you're doing (which doesn't seem to be the case here.)

**Comment by gdamore** [comment]
I think the question is answered here.  I'm closing it.
