### ISSUE TITLE
[question] How to run the server normally when running in REQ mode?

### ISSUE THREAD

**Issue by waxwax0099** [nanomsg/nng#1630]
I want to design a reliable delivery configuration function. Select the REQ/REP model.

Scene conditions:
1, The **client** connects to the server, and clinet runs in the **REP** model
2, **Server** listens to the port, the server runs in **REQ** mode, and will actively deliver the configuration to the client at a specific time

I have a question, in the server, how can I save the context corresponding to a specific client for subsequent sending messages?

**Comment by gdamore** [comment]
This protocol does not let you send directed messages to a specific client.

**Comment by waxwax0099** [comment]
Thank you.
I'm trying a way, register through nng_pipe_notify, apply a new context in the callback function, associate the pipe with the context, keep the context to communicate with the specific client in the future.
But the problem is, how to associate the pipe with the newly created context?

**Comment by gdamore** [comment]
Generally what you want to do isn't possible for ordinary applications.  This kind of thing is the purview of protocol implementations -- you could see for example how REQ/REP do it, or how PAIRv1 does it.

The goal of Scalability Protocols is to solve these common kinds of problems for you, so that you don't have to do it yourself.  Unfortunately, not everyone's scenario always fits, but a significant percentage of them do.
