### ISSUE TITLE
Request/Reply Protocol Throughput and Scalability

### ISSUE THREAD

**Issue by Alexander-Shukaev** [nanomsg/nng#1663]
Sending 100K requests and receiving 100K corresponding responses (512 bytes payload size) takes 40+ seconds using asynchronous IO and contexts.  Flame graph profiling shows:

![nng](https://github.com/nanomsg/nng/assets/911281/125118dd-41df-4814-9eef-08d6a31c8d3b)

Contexts are created on-demand using high-performance object pool and memory allocator.  Both requester and replier are within the same process.  Most of the logic is within send/receive callbacks and is very simple, just enough to deal with message extraction/preparation/responding.  The kick off of the test is that requester sends a burst of 100K messages in a loop from main thread (again using contexts and AIO, so no blocking).  As far as I can see, most of the time is consumed by `req0_run_send_queue`, not by application code...  Would you happen to know the reason why?  Could it be that there are too many contexts created in a burst and NNG scheduler is overwhelmed somehow as a result?

** Environment Details **
 - NNG 1.5.2
 - Red Hat Enterprise Linux Server release 7.3 (Maipo)
 - g++ (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
 - Static library

**Comment by Alexander-Shukaev** [comment]
I was seem to be right about overwhelming scheduler.  I did limit the number of contexts (by a maximum number of concurrent threads as per system for now (56 in my case)) and when trying to send a request when this limit is exceeded I back off with a spinlock until context object could be reused (i.e. one of the previously used ones is recycled as a corresponding reply was received on it).  This boosted throughput and is now roughly similar to numbers from #1528: 25K rr/s for `inproc` and 20K rr/s for `tcp` and `ipc`.  This is still very low I'd say.  Could someone shed some light as to what could the problem?  Is `req`/`rep` protocol in general less efficient?  It cannot be that it's that slow...  My expectation would be to reach at least from 50K to 100K rr/s.

**Comment by Alexander-Shukaev** [comment]
One more update.  I went ahead to test how independents pairs of `req`/`rep` scale (within on process) using different (randomly chosen) transports.  So multiple test runs with 2, 4, 6, 8, and etc. pairs, each of which is doing the same thing: bursting 100K requests/replies (where sending loop is run in a separate dedicated thread for each of them to make it fully concurrent).  The observation is that 6 pairs top the throughput (altogether) at 100K-110K rr/s (with 3.5 GiB/s of data exchanged), while 8 pairs already perform worse at 90K rr/s, and 10 pairs drop even further to 80K rr/s, at 32 pairs it already falls off a cliff down to 25K rr/s (which is a performance of 1 pair standalone essentially).

**Comment by gdamore** [comment]
Yes. The design here is that we won't have lots of contexts - one per cpu core is expected with some allowance made for long running tasks.  

The search for a matching entry is linear and it isn't surprising that more contexts hurt performance.  We could probably explore better data structures here to make this O(1) instead of O(N).

**Comment by Alexander-Shukaev** [comment]
How about having a direct pointer to context object stitched into a header of request?

**Comment by Alexander-Shukaev** [comment]
@gdamore, a kind bump, I wouldn't want this topic to die off.

**Comment by gdamore** [comment]
A pointer stitched in as you suggest would not be acceptable as it would be a huge security risk.

What needs to be done is to replace the simple array look up with a hash table, I think.  This would improve the scalability of this.

**Comment by axelriet** [comment]
I'm new to nng and I have to say the first impression is spectacular. The code is super-well written, and the comments are insightful. I also see that tremendous efforts have been devoted to ensure correctness and that is great! However, I, too, see perf issues that make nng difficult to consider. I get that for anything where a network operation is involved, the network latency and throughput are likely to be the limiting factors, but for ipc and inproc scenarios, I find nng to be more than 100x slower than zmq, which is not acceptable for my use. I'm talking 5-6M msg/s vs 40K msg/s using the existing inproc_thr 128 1000000 test on both. The perf issues lie in making nng both threadsafe and more POSIX compliant. I'll substantiate with examples: using an int socket handle may be more satisfying than a pvoid. However (as noted elsewhere), this implies a mapping currently made through a linear search, which is not a problem per-se unless one has many sockets. The problem is the search is protected by a write lock, which is unwarranted. I traced through nng_send() at line 44 of cplusplus_pair.cc, which uses inproc, and I lost track of the number of locks taken on that code path. Look for example at nni_msg_alloc(402-403) where one sees a call to nni_atomic_init() followed by nni_atomic_set() while a simple m->m_refcnt = 1; was sufficient here: the function owns m, no one is going to touch it. The first call resolves to InterlockedExchange() to set the value to zero (it is already 0 as NNI_ALLOC_STRUCT calls calloc() and the second to another InterlockedExchange() to set the value to 1. Interlocked calls place a lock on the memory bus and act as full barriers. The correct, portable way to make this assignment is to use WriteRelease(&m->m_refcnt, 1); which resolves exactly to m->m_refcnt = 1; on Intel, and executes thousands of times faster than the two InterlockedExchange() calls. Then comes nng_sendmsg() with the write lock around the search, where using a pvoid as socket handle would be a few thousand times faster again, then nni_sock_rele() taking a write lock, then the (optional) stats incs in pair1_sock_send() the write lock around the actual sending, an nni_atomic_get64() within nni_pollable_clear() as nni_lmq_full() returned true while it was never allocated - an InterlockedExchangeAdd64() while a ReadAcquire64() is all that's needed, another write lock taken in nni_aio_finish_impl() and yet another write lock in nni_task_dispatch(), another write lock in inproc_pipe_send(), one write lock in nni_aio_schedule(), yet another write lock taken in nni_aio_finish_impl() and one final (I think) in nni_sock_rele() at nng_sendmsg(198) - It will be difficult to make that code fast.  I read that excessively complex state machines hindered nanomsg, I can say that excessive locking is hindering nng. This price should be optional and not imposed on everyone. I would suggest 1) lowering the POSIX bar and using a pvoid instead of an int and  2) Getting rid of thread safety and removing all the unnecessary locks, then reconsidering all uses of Interlocked functions (most of them can go away) and only keep whatever is necessary for the aio to work. From the clean overall design, there is a chance that this can be accomplished using alternate implementations of pluggable elements and keeping thread safety as an option for those who rely on it, for example, by introducing a slight change to the protocol string: "inproc:://blah" (double colons) would be the thread-safe version of everything while the existing "inproc://blah" would require strong socket-thread affinity and preclude sharing a socket across threads. So yes, I'm suggesting introducing a breaking change and the new default to be the fast version. I like nng more than I have considered, but that perf hit is a no-no.

**Comment by gdamore** [comment]
I'd also recommend testing tip -- there are a lot of performance improvements you are missing if you're still on 1.5.2.

**Comment by gdamore** [comment]
One important datum here:

You're using a single REQ client.  This is where the scalability problem lies.  REP does not suffer from this because we don't have to lookup a matching context ID on receive.

It's very very unusual (outside of benchmark specials) to have REQ clients with large numbers of contexts.  I can't really think of a use case for this.  More common is some relatively modest number of outstanding requests.

I still think this can be a hash table, but the priority is greatly reduced for me because I don't think it maps to real world problems.  (If this was on the REP side I'd take it far far more seriously.)

**Comment by Alexander-Shukaev** [comment]
So either we have different expectations to REQ/REP concept or I am missing something with respect to documentation/understanding how to use it.

My "impression" or otherwise expectation of this concept is to be able to achieve reliable request/response semantics (that I don't have to code myself) with minimum overhead.  I'm not sure if you're familiar with Kafka, though you most probably are, but the idea here is that requester can just bombard counterpart (in Kafka case, broker queue; in NNG case, other application) with requests in strictly ordered (queued) manner in a sense that if they are "produced" by the same thread (in REQ application), that ordering is guaranteed.  The advantage here is that, while the first `n` requests are being transported/processed (by REP)/responded (by REP and received by REQ)/(and potentially responses processed in potentially yet another thread of REQ application), the next `m` requests can be prepared and produced (sent).  You can think of it as a non-stop pipeline process which is highly efficient as there is no unnecessary idling in between these steps.  Now, if I had just one REQ context as you suggested, correct me if I am wrong, but to my understanding, this would imply that I can only send 1 request and until I received a response to it, I cannot send another one.  If that's the case, then this concept is not going to fly for high-performance ack-based (REQ/REP) communication.

**Comment by Alexander-Shukaev** [comment]
I forgot to mention, upgrading to 1.6 unfortunately didn't make any difference to scalability test...

**Comment by gdamore** [comment]
Sending a few should be fine.  Sending thousands from independent sockets (multiple peers as is typical for a server handling lots of clients) is also fine.  The problem is specific to a single client with lots of contexts.  You may have a use case for this but I don't believe this is typical. 

- Having said all that,I still think  we should fix it, but I don't think this problem impacts many users outside of synthetic benchmarks.

**Comment by Alexander-Shukaev** [comment]
We do want to build a large-scale system internally that is supposed to replace the old one with a crusty home-grown ack-based protocol, that is written in C.  It currently handles hundreds of billions of messages daily.  It does have these point-to-point communications at the heart of it, where it's particularly just 2 actors talking to each other, acking each message.  I've been researching what's on the market as I don't want to reinvent the wheel here and NNG was particularly appealing also due to its abstraction of `inproc`, `tcp`, and `ipc` concepts as this is also exactly the optimization that we wanted to take advantage in the new system (as to whether the actors are within the same process or machine or otherwise different network nodes...).  This makes this particular REQ/REP paradigm crucially important to us.  So, yes, it's a bit heartbreaking to hit that confirmed limitation now and to see that this would not be on your priority radar...  Nevertheless, keep up the good work and thank you!

**Comment by gdamore** [comment]
@Alexander-Shukaev  Are you actually planning to use lots of contexts on the *same* REQUEST socket?  Clearly the use case isn't one I have thought much about -- but it *should* have worked, the fact that we have this limitation here is an error of over sight not of intent.

**Comment by gdamore** [comment]
Ah... it is not the receive callback -- which is what I thought it was -- that's already an idhash table so O(1).  The *send* callback is what is taking time.  So let me look because my casual analysis from before was clearly wrong.

**Comment by gdamore** [comment]
Oh, the longest portion of the queue is the timer scheduling.  Interesting.  I'll look further.

**Comment by gdamore** [comment]
The surveyor has a similar problem btw.  All of these come down to the nni_timer facility which I had previously planned to remove anyway.

What I think we should do is just have a single timer (can be aio driven) for the entire socket.  It can wake at 1s granularity to see if a retry is needed.  It's unlikely that folks will choose retry timers longer than that -- but we can also make that wake up interval configurable.  Furthermore, we should make sure that we don't wake if there are no requests needing a check.

The draw back with that approach is that we may be waking every second only to do nothing, but I think we can tolerate this.

I will be happy to throw away the nni_timer thing.

**Comment by gdamore** [comment]
The above PR is my first swag at this.  It may need work.

**Comment by gdamore** [comment]
This also should significantly reduce the amount of lock activity for REQ sockets.

**Comment by gdamore** [comment]
I've merged the fix for what I believe is the main problem.  Please do verify, and if you find otherwise, let me know.  (Open another tick and reference this one.)

**Comment by Alexander-Shukaev** [comment]
Thank you, @gdamore, will test tomorrow ASAP!
