### ISSUE TITLE
How does tcp actively send different information to different clients?

### ISSUE THREAD

**Issue by 1397436824** [nanomsg/nng#1674]

**Comment by 1397436824** [comment]
For example, if four nodes are connected to the server, how can I choose to actively send information to three of them?

**Comment by gdamore** [comment]
This is handled by the "protocol" ... and be aware that it's not just a single TCP stream.  Instead protocols that can broadcast send to multiple streams.

For PUB/SUB, the message is sent to all listeners, but then the protocol code on the listener filters out so that the application only sees the messages they are subscribed to.

For REQ/REP, the code examines the headers from the received sockets and routes the reply back to the appropriate sender.  (These are SP headers, not part of TCP/IP.)

There are no patterns today that allow you to selectively indicate which 3 out of 4 (or more) destinations to send to.  Nothing prevents such a pattern being created, if there was a use case for it.  The problem with these things is usually describing the semantics reasonably -- i.e. how should an application decide which "peers" to send to?  What would that API look like?

**Comment by gdamore** [comment]
I'm going to close this as it's just a question, and doesn't indicate a request for code changes.
