### ISSUE TITLE
[Question] nng_stream and nng_aio caused a panic

### ISSUE THREAD

**Issue by alawn-wang** [nanomsg/nng#1720]
**Describe the bug**
I have a struct just like this

```
struct InternetSteam {
	nng_aio* aio_read_;
	nng_aio* aio_write_;
	nng_stream* s_;
	uint8_t* rec_buffer;
	int rec_buffer_len;
};
```

it do a simple thing, receive data from other client and send message back without any change immediatly.

**Expected behavior**
It can receive data and send it back correctly.

**Actual Behavior**
if another client send data frenquently, the server will crash when 'send()' message back.

1. In debug version it will give panic, such like _'panic: D:\env\nng\src\core\aio.c: 335: assert err: !nni_aio_list_active(aio)'_

2. In release version it will give panic, such like _'nni_panic("appending node already on a list or not inited");'_ , it crashed at websocket.c->`ws_str_send()`->`nni_list_append(&ws->sendq, aio)`;

**To Reproduce**
a simple code  just like this

```
void recv(InternetSteam* stream) {
	nng_iov iov;
	iov.iov_buf = stream->rec_buffer;
	iov.iov_len = stream->rec_buffer_len;
	nng_aio_set_iov(stream->aio_read_, 1, &iov);
	nng_stream_recv(stream->s_, stream->aio_read_);
}

void init_stream(InternetSteam* stream) {
	int rv;
	stream->aio_read_ = NULL;
	stream->rec_buffer = (uint8_t*)malloc(32768);
	stream->rec_buffer_len = 32768;
	if (rv = nng_aio_alloc(&stream->aio_read_,stream_recv_cb,stream)!= 0) {
		fatal("nng_aio_alloc read", rv);
	}
	if ((rv = nng_aio_alloc(&stream->aio_write_, nullptr, nullptr)) != 0) {
		fatal("nng_aio_alloc write", rv);
	}
	recv(stream);

}

void stream_recv_cb(void* arg)
{
	InternetSteam* stream = (InternetSteam*)arg;
	int rv = nng_aio_result(stream->aio_read_);
	switch (rv) {
	case 0: {
		recv(stream);
		send(stream);
		break;
	}
	case NNG_ECLOSED: {
		break;
	}
	default:
		break;
	}
}

void send(InternetSteam* stream)
{
	int len = nng_aio_count(stream->aio_read_);

	nng_iov iov;
	iov.iov_buf = (void*)stream->rec_buffer;
	iov.iov_len = len;
	int rv = nng_aio_set_iov(stream->aio_write_, 1, &iov);
	if (rv != 0) {
		fatal("nng_aio_set_iov", rv);
	}
	nng_stream_send(stream->s_, stream->aio_write_);
	nng_aio_wait(stream->aio_write_);
	rv = nng_aio_result(stream->aio_write_);
	if (rv != 0) {
		fatal("nng_aio_result", rv);
	}
}
```

I'am sure the data can be received correctly,

** Environment Details **
 - NNG 1.6.0
 - MSVC  cpluscplus
 - static lib

**Additional context**
**I have tried another way to slove this problem. use a **unordered_map** to store the received data, and send the data in unordered_map at another thread created by my self. it will run corrctly. But i not sure why the way as beyond is incorrect.**

**Comment by gdamore** [comment]
The code you have above suffers from a defect.

You're using the same send aio, and not waiting for any previous one to complete.  (You do wait in "send"), but you can have multiple aio receive callbacks occuring in this circumstance leading to an inadvertent reuse of the send aio concurrently.

My recommendation here is to do one of two things:

1. If this is truly meant to be synchronous, and *single threaded*, you *can* simply re-order the calls to send and receive, so that you don't try to start another receive operation until the previous send is complete.  (Because you call nng_aio_wait() this will be guaranteed.)  HOWEVER, calling nng_aio_wait() from a callback is *NOT* something you should do, because it means that thread is stuck and cannot proceed, which can actually cause a deadlock in the application if you cause more threads to be in this state than the number of threads in the pool for dispatching callbacks.).

2. **Far** better is to refactor this code to slightly use just a single AIO object and a simple state machine, and use the same callback.  The callback should look at the state to know what the next action to perform is, and of course update the state so that the next time it gets called it knows whether to send or receive.  This will have the advantage of not leaving any thread blocked, which will prevent the deadlock mentioned above, and be gentler on system resources.

Ultimately the second approach can be used with many aios to build a concurrent application supporting many streams, where the actions on a given stream are always synchronous, but you have many of them.  It also is a bit lighter in terms of resources since there is only a single aio, and you can avoid blocking.

Anyway, I'm going to close this because there is no NNG bug here -- although you do have a bug in *your* code.
