### ISSUE TITLE
Is websocket support a multiplexing?

### ISSUE THREAD

**Issue by alawn-wang** [nanomsg/nng#1768]
Hi,  gdamore, I want to boardcast a information use websocket, and I notice that websocket supports exetension which can let multi connect shared one tcp stream.  Is nng support this feature? or how can i implement this feature simply?

**Comment by gdamore** [comment]
We do not support multiplexing multiple connections on a single TCP connection.  And really, you don't want to use it unless you have a serious problem with the number of concurrent connections -- because you will encounter head-of-line blocking issues.

In fact, as far as I am aware, RFC 6455 does not have any notion of multiplexing multiple websocket connections over a single TCP connection. 

There are libraries that let you build such things on top of lower layer streams, but that requires both ends to use the same approach, and, as far as I know, there is no standard for it.

NNG could conceivably implement its own multiplexing logic, but I am strong disinclined to do so because it would likely create more problems than it solves.

**Comment by gdamore** [comment]
Closing as this was a question, and I'm not going to implement this as a feature.
