### ISSUE TITLE
Anomalous behavior of tcp flows

### ISSUE THREAD

**Issue by RanMaoyi** [nanomsg/nng#1773]
**Describe the bug**
When using rep/req as message communication, an abnormal behavior was found. The client sent a request to the server, and the server returned a certain amount of messages to the client after receiving the request (note: the error occurred when the message was large).

The anomaly is that it gets stuck at 0 seconds, then it continues to send at 60 seconds, and at the end of the send, it produces a large number of alloc, which should be caused by dirty data readout.

It is suspected that the problem may be caused by nng's handling of EAGAIN incorrectly, because the kernel returned EAGAIN when it was stuck.

The following is the crawled pcap data for reference analysis.

**Expected behavior**
The program does not get stuck and does not read dirty data

**Actual Behavior**
The program gets stuck and reads dirty data

**To Reproduce**
Not yet, but you can try to construct this scenario using nng, sending a lot of data in a very short time,

** Environment Details **
 - NNG version
 - Operating system and version
 - Compiler and language used
 - Shared or static library

**Additional context**

[0206_05_consumer_tcp.pcap.zip](https://github.com/nanomsg/nng/files/14321264/0206_05_consumer_tcp.pcap.zip)

**Comment by JaylinYu** [comment]
hi Garrett, this is a Security vulnerability rather than a performance issue. While transport reads dirty data, it causes buffer overflow by allocating an extremely long msg.

**Comment by gdamore** [comment]
I need to look at the pcap file.  It would be good to have more of the data that I requested ... the NNG version, the OS, etc.  Anything that would help me understand the observed behavior and the context it is in.

**Comment by gdamore** [comment]
It looks like you're trying to send a 10 MB record (roughly) over this.  (It looks like a JSON record containing a "dumpfile" that is mostly filled with "61" (bytes 0x36 0x31).  This is request ID 0xf0820885.   (The request was the word "dumpfile", and this appears to be coming back as JSON reply.).  I have not added up all the payload bits to make sure they add up to the correct payload size -- and the last message of that reply does not include the end of the message (only 34 bytes of TCP data were included, but the payload was 32K).  So barring that, the traffic looks correct.

60 seconds later it looks like we try to do a retry using the same request ID.  So it appears that the REQ socket didn't get the whole message in time.   If it was stuck in a debugger, this could explain it.

Right now that's all I can determine from what is sent to me. I don't see any evidence of a security bug or memory corruption here. 

The maximum allocation used for receives is determined by a socket option.  

The only possible problem I see here that could cause confusion is if the sender (the REP side) somehow failed to properly frame the message (did not send the entire number of bytes that were specified in the message length).  I would expect that this cannot happen with TCP.  We do actually write() until we have no more bytes to write.

That said, I'm more than happy to add a 10MB send test to the req test suite just to verify it.  (We do use some large sends somewhere in the test suite, but I'm not sure where.)

**Comment by gdamore** [comment]
I've added a test that exercises almost precisely what is described here:

https://github.com/nanomsg/nng/commit/b4512a2ff043e09370a49f951e0ed2bd9a946913

On Windows this uses TCP, but on POSIX systems the test uses socketpair() connections.  The underlying behavior should be analogous in both cases.  The test passes without any significant challenge.

So right now I'm not able able to understand what the problem is that you're reporting here -- except that if if the REQ socket receiver is paused for some reason (or not able to receive the reply for some reason) then that would cause this behavior, although I'd still expect that the retry doesn't take place because we should be able to read the resulting data before sending out the retry.

**Comment by JaylinYu** [comment]
let me elaborate it a bit more. 

The case is, it uses REQ/REP protocol for locale communication, and large payloads to deliver the Stream processing feature. Taking TCP as transport, sometimes using 127.0.0.1 loopback. Somehow, it triggers EAGAIN on the sending side, apparently a networking congestion happens, as a result, the receiving side experiences 1min blocking, and reads out some dirty data after recover by retrying. 
If the RECVMAX is not being set properly, NNG TCP transport would alloc a huge huge length of msg from the dirty data, I don't know why it penetrates the SP header, but it shall not happen.

The pcap file is only a way to help you understand the context.

**Comment by JaylinYu** [comment]
Well, the outcome of the pcap file is our client crashed due to ran out of memory. From the view of the send client, nothing goes wrong, it writes all data to socket at once(except EAGAIN). Dont know how come TCP returns dirty data to socket read of receiving side, but I think there is at least one thing is possible for improving: add a congestion control method if `sendmsg` returns EAGAIN? some backoff algo maybe.

Perhaps also adding a msg header in SP, in case diety data penetrates.

**Comment by gdamore** [comment]
No way to add a message header short of adding an intermediate framing layer in NNG, and I'm loathe to do that.  Part of the beauty of SP is that it is simple.  If you want to send huge messages, it should work if you have big enough buffers.  If you don't like that, then applications can do their own framing.

As far as EAGAIN, we don't spin -- we back off until the OS tells us there is data (or room in the socket buffer for sending)  via epoll(), kqueue(), or similar mechanism (depends on the OS).  There really is nothing else to do.

We don't restart the message, we just keep track of what we already transferred, and continue where we left off.  This way it looks like an unbroken stream.  It's actually quite simple.

Anyway, as it appears that this is due to problems outside of the control of NNG (too large message size crashing the client), I am going to close the issue.  (Btw, this precise problem is why there is NNG_RECVMAXSZ -- it defaults to a reasonable small value for use in hostile networks -- 1MB I think -- and if you want to support larger values you set it to a larger value but be advised it requires allocating memory to hold the entire message.  (Actually probably 2x that because of message queue depth)

I am thinking about future protocol extensions for this value to be communicated as part of the connection phase, so that senders could get a notice when they try to send a message that is too large.  But it's for later.
