### ISSUE TITLE
Windows - ipc_send_cb crash

### ISSUE THREAD

**Issue by mikisch81** [nanomsg/nng#1930]
**Describe the bug**
Crash in ipc_send_cb in stressed reqrep example

**Expected behavior**
Client and server run without any crash

**Actual Behavior**
At one point client calls `nng_send` and a crash happens in the invocation of `ipc_send_cb`.

**To Reproduce**
Run the modified version of the `reqrep` example with ipc transport from here: [https://gist.github.com/mikisch81/428c4ad87afcc1c8881b282cd5e80eb3](https://gist.github.com/mikisch81/428c4ad87afcc1c8881b282cd5e80eb3)

This example also was used to reproduce #1827 and #1837

Server: `reqrep.exe server ipc://testing.nng`
Client: `reqrep.exe client ipc://testing.nng`

** Environment Details **
 - NNG version: 1.9.0
 - Operating system and version: Windows 10
 - Compiler and language used: C/C++ clang
 - Shared or static library: static

**Additional context**

![Screenshot 2024-11-12 at 11 15 44 AM](https://github.com/user-attachments/assets/71050029-9477-4425-b537-5a744ad07769)

**Comment by gdamore** [comment]
i think I may have finally gotten this one figured out.  The accept logic for Windows IPC is not checking the result of `nni_aio_schedule`, which means it can wind up in a use-after-free scenario.

There are also some problems with the aio framework right now, that I think I have figured out and have a PR against the development (2.0) branch that includes the fixes.  (They are part of a much larger PR...). I'll probably cherry pick those fixes into the stable branch because I think they are pretty important.

**Comment by gdamore** [comment]
Can you please have a look at the top of the "stable" branch and let me know if it reproduces there?

**Comment by gdamore** [comment]
I believe this is closed both in stable, and in development.  THe whole framework has had major surgery for the "main" development branch as well.

I'm closing it for now.  Let me know if for some reason it is *not* fixed.
