### ISSUE TITLE
Adding version definitions

### ISSUE THREAD

**Issue by aby-github** [nanomsg/nng#237]
I want to request the addition of version numbers in the header or an API to call. I am building a Python wrapper and it would help if I could keep track of the version.

I know this might be a bit soon due to the rapid development that nng is going through.

Thank you.

**Comment by gdamore** [comment]
it is definitely my intention to use semver to version both the API and the
ABI. I havent done so yet as we are still 0.0 (prerelease).

I will think about getting this done tho.

**Comment by gdamore** [comment]
Do you have preferences for runtime vs. compile time identification?  Also ABI versioning?

**Comment by aby-github** [comment]
For my purposes I would just need API, and compile time would be
preferable.

**Comment by gdamore** [comment]
So nanomsg uses ABI versions, which I think are somewhat awkward.  It does this because of libtool restrictions.  We will still need that at some point, but I think that's orthogonal to *API* versions.

What I'd like to do is use semver for nng, which means that we will version the entire nng and the API that goes with it together (separating the two makes no sense as the API *is* the primary thing that nng delivers). 

I'll probably stick something in the NNG header file to this end.

**Comment by gdamore** [comment]
Ok, 0.5.0 fixes this -- see NNG_MAJOR_VERSION, NNG_MINOR_VERSION, and NNG_PATCH_VERSION in the nng.h header file.  Fixed in 48a1033794eb423c3f216bba02abd61240306e0d
