### ISSUE TITLE
Please clarify impact of trademark on "nng" and "nanomsg"

### ISSUE THREAD

**Issue by kiatoa** [nanomsg/nng#239]
I submitted a project of mine that uses nanomsg (someday to switch to nng) to nongnu (https://savannah.gnu.org/register/) but they are balking at the use of nanomsg due to the trademark.

The comment was: "There is some concern about nanomsg: its license text says its name is trademarked, without stating a trademark policy. Trademarks may render software proprietary. "

Can you add some wording or policy statement to the trademark/copyright section that assures that the trademark will not be used to render nanomsg or nng proprietary?

**Comment by gdamore** [comment]
That’s an interesting question.  I don’t really have a policy per se, I
just don’t want others using the name for conflicting or confusing
purposes.

Do they have some sample language?  I mean even “Linux” is a trademarked
name.  My understanding is that the license (MIT) governs use of the
“code”, but the trademark governs use of the “name” — and that the two are
largely orthogonal.

I presume you’re submitting your package that consumes nanomsg/nng and not
submitting nanomsg/nng itself, right?

 - Garrett

**Comment by kiatoa** [comment]
The discussion regarding the trademark is at https://savannah.gnu.org/task/?14832.

I'm submitting a package that consumes nanomsg/nng. I have posted the URL to this discussion at the savannah URL given above. I suspect that simply stating your goal of preventing confusion, conflicting usage etc. would be enough but perhaps Ineiev from the gnu site will comment more directly. Thanks.

**Comment by gdamore** [comment]
I can see that the problem is that the "trademark" statement is in the actual license text, and that may be what is upsetting.  (Martin did that with nanomsg.  I never place trademark information in license files -- that information belongs on printed matter where the name is actually used.  So, if you look at nng, I think you will find that it does not include the trademark notice on anything except some of the documentation files.)

I would be amenable to ripping off the trademark statement from the license statements.  At present I own the trademark, so I think it would be ok for me to make that decision, even for files that Martin originally authored.

If the savannah people have more questions about this, or advice on how to proceed, please let me know.  My main goal in the licensing is to make sure that there are as few barriers to use of nanomsg and nng as possible, and if this trademark statement is creating a barrier, that was assuredly never the intent.

**Comment by gdamore** [comment]
I've written up a policy: 

http://nanomsg.org/trademarks.html

Hopefully that makes it all clear!

**Comment by kiatoa** [comment]
Thanks for the expanded page explaining the trademark situation. It helped. Thanks also for nanomsg.
