### ISSUE TITLE
macOS pthread locks *hurt*

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#354]
Apple, in their infinite wisdom, has seen fit to provide "fairness" guarantees on pthread locks, such that an application will be badly penalized for dropping and reacquiring a mutex.  This has been measured to have impacts of up to 20 us in the local IPC latency test just adding a single uncontended mutex.

We didn't design with "fairness" in mind, and instead expect that pthread locks are *cheap*.

There is an undocumented lock, os_unfair_lock (and documented but deprecated OSSpinLock), which is superior on this platform for our needs (extremely cheap locking).

It looks like we need to create a darwin platform proper that uses these locks, but we will need to think about how to make this work with condition variables.

Note that this isn't required for *functionality*, but this change may be needed to make it work *performantly* on macOS.

Some links for reference:

https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/spinlock.3.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1137963#c0

**Comment by gdamore** [comment]
So there may be other cases where spinlocks would be nice.  These things don't have to synchronize against clocks, so they can be lighter weight.  We have a number of use cases for these in the current code.   Spinlocks are superior to atomics in some respects because they can synchronize multiple items.

**Comment by gdamore** [comment]
The more time I spent diagnosing macOS performance, the less impressed I am with the platform.  Frankly, nobody should really use that platform for anything performance sensitive.   Linux and Windows both far outperform it.

**Comment by joemoulton** [comment]
While I couldn't image working with and writing cross-platform code against all platforms, OSX is the only reliable of the big 3 for real-time audio latencies (or even just heavy loaded pipeline audio filtering + recording without dropouts) because of Core Audio (because the underlying rendering pipeline and real-time threads issued are managed by the kernel).  Metal is legit too, though I wish it could be exposed in a public C or even C++ api that didn't have to rely on calling the obj-c runtime and I would kill for some NVidia hardware on a Mac.  For client facing applications having UIKit and ApplicationKit built into the OS is more versatile, high definition display ready and a massive time saver over having to develop native UI with Windows/Linux or use Qt or even compared to Android UI development.  GCD thread pooling IMO beats Windows threads and direct pthread use hands down, but you came from an illumos background where that doesn't impress you.  I also think it has the most impressive kernel architecture of the major platforms (for a kernel architecture built 20 years ago, excluding true RT kernels).

Anyway, I'm not sure what resource(s) you're trying to synchronize with locks and I just started using nng two days ago so I'm not all that familiar with any of its non-client facing code yet, but I've never gotten anywhere with mutexes or locks on OSX/iOS.  As a general rule for real-time programming on any platform though, don't attempt to use locks on a "real-time" thread. They are terrible for performance. I would classify any thread you are trying to squeeze utmost performance out of as a "real-time" thread on non-realtime platforms. In this case I would probably try to use some kernel level mechanism you can idle on and wait for events like a kqueue or a pipe or both, and synchronize the two (or more) contexts contending for resources in that manner.  Or maybe you just need some shared memory they can all access.  The former is what I am doing in my cross-platform graphics windowing libraries on the OSX side for interthread and interprocess event communication and idling because they are the only userspace-kernelspace messaging mechanisms that deliver on latency and performance but still I never try to synchronize resources between threads in a pipeline where one isn't explicitly downstream of the other (allowing you to implement some non-lock based sync strategy).  Moreover, no matter the [desktop] platform, I always see network handling abstracted into the main thread of a dedicated "real-time" process that can be elevated to the highest priority the system will allow userspace code to elevate.  This is the best performance you are going to be able to get out of any thread in any process without perhaps writing a kernel space driver.  But you probably know all of this and still have good reason to use locks and I am just coming off as really annoying.  I've commented on some other issues, but, again, I may be able to help you out with performance and general feature implementation on Darwin platforms once I get up to speed.

I also wonder if the really long aio_wait time I am seeing on iOS has to do with this.  I haven't tested on macOS yet.

**Comment by gdamore** [comment]
Locking is not terrible intrinsically, although it can hurt if you have *contention* or if care is not taken to prevent false aliasing of locks on cache line boundaries.

The problem is that under macOS just dropping and reacquiring a lock guarantees a context switch because they have a "fair share" attribute that is unlike locks on pretty much any other platform.  They are extremely heavy weight, and reach down into the kernel.  Normally an uncontended lock should not need to do that -- it should instead just be not more than a few simple instructions beyond the machine level CAS instruction (compare-and-set).  Apple has chosen to apply additional semantics that make this not true, and greatly penalize otherwise reasonable pthread lock usage.

Btw, I know lots about audio performance and real-time.  I basically am the guy behind the audio mixer and framework that illumos and Solaris uses (the Boomer project).

Btw, "Real Time" does not necessarily mean performant, or more performant.  In some cases, the effort to provide true hard real-time actually will reduce overall system performance, in order to guarantee minimum latencies and service times.  And usually those minimums are rather generous.  (I don't think I've seen any RTOS that provides any guarantees of sub-millisecond latencies, but I've often done work that needed single digit microsecond processing.)

**Comment by joemoulton** [comment]
I don't doubt your real-time cred.  If there is one thing that we can agree on is that locks ARE NOT performant on Darwin platforms.

I've only delivered real-time systems that involve latencies in the ms range because our requirements are based on graphics frames generated and these were on commercial OSes.  I've never used Redhawk but they promise microsecond userspace event latencies:

[Concurrent RedHawk Linux](https://www.concurrent-rt.com/products/redhawk-linux/)

**Comment by joemoulton** [comment]
Also when I say Core Audio Real Time Thread know that this is the nomenclature that Core Audio uses and is not the same a hard or soft real-time requirement.  Sometimes when I use "real-time" in the posts above I am just referring to a thread on a commercial OS being as performant as possible (such as a Windows process elevating to REALTIME priority class) and sometimes I am referring to a soft real-time requirment because nobody dies if the requirement isn't met.

**Comment by gdamore** [comment]
REALTIME priority class doesn't make anything more performant.  It just is a higher level of scheduling class, and (for typical OSs) runs at even higher priority than interrupt handlers (depending on hardware, and type of interrupt handler... etc. etc.)  Generally placing something in a REALTIME priority scheduling class is contra-indicated.

Having said all that, yes, there are soft real-time requirements (not generally actually guaranteed) for proper handling of video and audio (and some other kinds of isochronous processing.)

I generally prefer to avoid REALTIME as an adjective in all cases except when there are specific scheduling guarantees required.  I also prefer to avoid the associated scheduler priorities unless those guarantees are required -- because real time processing is much more susceptible to failures like priority inversion and hard lockups in the face of programming errors.

**Comment by joemoulton** [comment]
"It just is a higher level of scheduling class"

Yes, I can agree that "performant" is not the best choice of words on my part.  On Darwin platforms these "REALTIME" threads are scheduled with finer timing granularity than standard threads because they are scheduled by the kernel which allows them to meet those soft "real-time" requirements.  On Win32 and OSX I elevate a dedicated process and distribute all vertical retrace timing events back to my application.  On Windows I do this with the REALTIME priority class and I know it is ok to do so because I am making a single kernel space call and distributing an event back to my application.  In fact I'm pretty sure this is what all VR HMD drivers do.

You are right you shouldn't do lots things on threads elevated to realtime priority and if they could result in priority inversion you probably shouldn't be doing it there in the first place.  However, you may still benefit priority-wise from running on the main thread of a dedicated process without elevation on macOS.  

Not that any of this has anything to do with or is going to solve the issue Darwin uncontended pthread locks reaching down into kernel space if you are still set on using locks.  But I think my underlying point there was -- if you wouldn't put any kind of Darwin provided lock system provided "Real Time" thread like that provided by a Core Audio context for performance reasons, why would you expect a Darwin provided lock to deliver in any other context you were trying to achieve performance with?

**Comment by gdamore** [comment]
I definitely need locks.  That's not negotiable. 

For some of my lock uses, I may be able to replace them with spinlocks.

For others, that won't work, because I am using these in combination with condition variables.

**Comment by joemoulton** [comment]
I assume you need locks primarily for managing asynchronous writes to file descriptors when the data is large enough that the operation is not atomic.  Correct me if I am wrong.

I understand why you want to use atomic spinlocks based on Apple's article comparing them to mutex locks. But they have been deprecated for a reason and they are going to kill performance because they don't idle an and they can lead to priority inversions.  Really all you can do is roll you own lock, semaphore or priority queue implementation that idles and waits for distributed events on kqueue.  It is the only messaging mechanism that can avoid the user space -> kernel space -> user space dilemma.

**Comment by gdamore** [comment]
So, the issue is that Darwin has made some weird choice (apparently?) to make their mutexes reach into the kernel, even uncontended.  They are the only OS I know that doesn't at least try a spin in user space, (even just one or two spins) and bypass the kernel on non-contended locks.

Their answer to this is libdispatch, which basically is classic Apple saying "all you other guys who've been building systems for decades have been doing it wrong -- if you want to not suck on our platform you have to use our fancy schmancy newfangled thing that only exists on our platform, which means your application is probably not going to be portable anywhere else, which suits us fine.  Welcome to the Garden."

I think Apple is Just Wrong on this front.  They may have unusual constraints because of the way mach is cobbled up underneath in some kind of hybrid -- I'm not familiar enough with their scheduler to know what the limits of those constraints are.

It's interesting that Go, which doesn't use this stuff at all, seems to work really quite well on macOS.  But basically they don't use libc or libpthread at all for their runtime.

Anyway, I might cobble up my own spinlocks for Darwin, because I do have the stdatomic.h and it really won't be hard to do. 

Btw, the concern about spinlocks and priority inversions -- well again, if you're using this stuff from realtime priorities, you're screwed.  But, if you're using spinlocks sensibly, you won't be blocking, so the priority inversion problem shouldn't be an issue unless you have more higher priority threads than you have cores.  It would also be possible to build a hybrid lock with a spinlock and a mutex, that would perform well uncontended (or very lightly contended), and fall back to mutex for the case where contention exists.

**Comment by joemoulton** [comment]
GCD is just a thread pool implementation on top of the OS provided threading mechanisms.  A message queue implemented via a thread pool is a de-facto alternative thread sync solution to outdated locking on any platform.  Are you using locks on Win32 as well?  Yeesh.

It's 2020.  Please stop advocating locks for thread sync.

**Comment by gdamore** [comment]
Wow joe.  Just wow.  Thread pools don't eliminate the need for locking -- *unless* you use a fully serialized model in which case you're back to running single threaded, and really relying on the dispatch implementation to do the locking for you.  In fact, if you look deep inside NNG, you'll see that there are some of those approaches used here.  (Have a look at the pollq worker code for example.)

Please take your Kool-Aid stand elsewhere.

**Comment by gdamore** [comment]
In #1086 I pointed that it seems like there may be some relief to this problem:

PTHREAD_MUTEX_POLICY_FIRSTFIT_NP 

We can use a first-fit lock policy, and avoid the case where we immediately (and always) drop into the kernel to provide fair share locking.  This is claimed to reduce the lock cost by like an order of magnitude.  Some testing is desirable to verify this claim.

**Comment by gdamore** [comment]
So the docs I've seen indicate that this capability is both *new* in macOS 10.14 (which isn't really all that new), and *default*.  It looks like Apple heard us. 

I'll upgrade my admittedly older system and see what happens.

**Comment by gdamore** [comment]
So just in upgrading to catalina (10.15) from 10.13 my latency dropped by more than 50% -- the inproc test numbers were up at around 48 us, and now they are right around 20 us.

This is a *huge* difference.  Anyone using NNG (or pobably anything else that is threaded and cares about locks) should probably consider upgrading to catalina (or at least 10.14) asap.

**Comment by gdamore** [comment]
On that note, I'm considering this issue *closed*.  Apple fixed it for us. :-)
