### ISSUE TITLE
open for discussion: http server module

### ISSUE THREAD

**Issue by questor** [nanomsg/nng#528]
I know that nng is not meant to be a general http server handling component, but to make it more useful it would help to refactor (or enhance) the http modul, for production and development purposes. some ideas: customized error pages (where you can print additional information and not only the error-code); possibility to add logging (for example when no handler was found for a url; and general logging in nng itself for things going on for the user (context handling) to be able to debug more easily not working applications).

I could understand that you first want to get the core system working and that http is only a supplemental, so I'm opening this ticket to discuss about your thoughts on this. Feel free to close this ticket if it's of no interest to you as I'm not using it for something in production (and it's also not planned), I'm doodling around the idea of a http-server with this library.

**Comment by gdamore** [comment]
I'm specifically interested in such things.  I had given some thought to a custom 404 error page.  An earlier version of the code had a callback dedicated for that (it was mostly like any other handler). 
 Customizing other errors gets kind of tricky, and is less valuable.  (The other error conditions are usually protocol failures, and less likely to be seen by humans who aren't developers.)

Logging is something I've not given a lot of thought towards, but certainly I can see it being useful for folks wanting to use some kind of web server framework -- most folks expect it.  I have very mixed feelings about logging in general, as it is IMO usually the last resort of the hopeless, and I think libraries should be very cautious about generating logs themselves.

What might make sense is to have the ability to register a logging handler, so that applications that want logs can supply their own handler.  This would keep nng from being opinionated about logging, which I think is a good design goal.

If logging is something you're specifically interested in, I'd be open to contributions here.  I'd like to see a callback registered (perhaps globally), and we could provide some builtin handlers for syslog or whatever makes sense on Windows.  The logging handler should be non-blocking if possible.  Logging should support printf() like formats, but I suspect that this will best be done in common code, so that the callback handler can just worry about fixed buffers.  A level and facility ala syslog (for filtering) should be provided too.

**Comment by gdamore** [comment]
I recommend you go ahead and file at least these as separate enhancement requests:

a) customizable error pages for HTTP server
b) logging support
