### ISSUE TITLE
could not a lot of big data buffer

### ISSUE THREAD

**Issue by xoyojank** [nanomsg/nng#555]
## NNG & Platform details.
nng 1.0.0
win10 64bit

## Expected Behavior
the data will be queued and never send failed

## Actual Behavior
after send a lot of data, nng_send always return EAGAIN

## Steps to Reproduce

- nng_pair1_open
- listen & dial to "ipc:///temp/test"
- send a lot of big data buffer(~300KB once)
- then nng_send with always return EAGAIN

this problem is similar to https://github.com/nanomsg/nanomsg/issues/961

**Comment by xoyojank** [comment]
if set the NNG_OPT_RECVBUF and NNG_OPT_SENDBUF to 4*1024, then some message send will not be received by the other pair.

**Comment by gdamore** [comment]
Are you sure that the sockets are connected?  Are at least some messages getting through?

Sending a lot of little messages is different than sending very large messages.  The protocol prevents messages larger than 1MB by default from passing.  This can be changed by setting NNG_OPT_RECVMAXSZ.

If you have a simple test program that exhibits the behavior, it would be helpful to me.

**Comment by xoyojank** [comment]
run for about one minute, there will be an exception. 
[test_pair.zip](https://github.com/nanomsg/nng/files/2147552/test_pair.zip)

**Comment by gdamore** [comment]
So I looked briefly at this (ran it in a debugger after making minor adjustments to make it work on macOS) and the error is occurring about 40 or so messages into the send.  You're attempting a nonblocking receive which may fail, but probably not, followed by a nonblocking send (unconditionally), followed by a short sleep.

The problem is that you can't blithely assume that a non-blocking send will work.  If the other side cannot keep up, the message buffer will back up, and backpressure will cause the send to fail -- this is entirely expected.

I don't see any calls to alter the queue depths either.  Changing the depth in terms of messages may help, but 4096 won't be enough necessarily, because you are trying to send some 10000 messages.  This is going to spin rather hard, because it takes some time to move 500 kb messages around.

I generally am not fond of NNG_FLAG_NONBLOCK (or nonblocking operations in general), as their normal use is in conjunction with a polled loop that polls on a descriptor to tell you when a non-blocking operation might succeed.  (This test program does not do that.)  A far better solution is to either make use of threads and blocking operations, or to use the callback support for asynchronous operations with nng_send_aio and nng_recv_aio.  This is a little more work, but its far more reliable and scalable.  You can look in the demo/async.c for an example of how to do this.

Given that you're using Windows, this callback mechanism is actually far more natural than any other approach you might come up with -- it matches typical coding approaches you might use with I/O completion ports.

So right now I don't see any "bug" in the behavior of the program, at least not in the library.  (The program is behaving unreasonably itself, due to deficiencies in its own design.)

If you're absolutely certain you want to use nonblocking operations, then you need to be prepared for (and deal with) NNG_FLAG_NONBLOCK. I further recommend you either make certain that your queue is adequately deep by setting NNG_OPT_SENDBUF to a value >= the total number of outstanding messages possible, or better yet coordinate it with some other polling or callback mechanism.   See NNG_OPT_SENDFD for a little more detail.  Again, I don't really recommend that unless you have no way to take advantage of the asynchronous I/O framework that already exists.
