### ISSUE TITLE
How would you recommed implementing server side filtering for pub/sub

### ISSUE THREAD

**Issue by niclar** [nanomsg/nng#587]
Hi how would you guys recommend implementing server side filtering using the nng primitives ?

The xpus/xsub zeromsg guarantees and interface has served well this far but I need something similar in nng.

One thought, is a staged approach with internal routing using pub/sub sockets & subscription request via a separate req/rep channel or something (i.e server pub -> server internal sub X server pub -> client sub ... ), but I'd prefer something with less complexity and overhead.

Thanks

Niclas

**Comment by gdamore** [comment]
You'd have to bake this yourself, unfortunately.  To be honest, I don't recommend this -- I'm looking at some future work that should help here.

Are you worried about bandwidth?  PUB/SUB isn't meant to push huge amounts of data, as its unreliable delivery means you will almost certainly miss stuff if you push too fast.

If you're not pegged on bandwidth, you might not need server side filtering.  Don't fall into the trap of believing you need something just because you think the theory (server side filtering) sounds better.

**Comment by gdamore** [comment]
Question.  Although ultimately long term we would like to do this work.  We really need a commercial sponsor for it though.  Closing for now though since this is not really an RFE.
