### ISSUE TITLE
Weird connect failures in dialer (multistress)

### ISSUE THREAD

**Issue by gdamore** [nanomsg/nng#653]
We are sometimes seeing unexplained "object closed" (NNG_ECLOSED) errors from the nng_dial() functions.  So far these seem to be come in the bus test of the dialer, and have mostly involved the IPC transport, but the failure count is not high enough for this to be conclusive yet.

My gut instinct is that the logic using the d->d_synch is a bit fragile, and to blame -- a better approach might be to replace this code path with an more idiomatic (for NNG at least) aio construct.

**Comment by gdamore** [comment]
Just got the same error in TCP.    Note that I've never seen this error on macOS, only Linux.

**Comment by gdamore** [comment]
Some further analysis -- the close looks like some remote error -- the underlying transport pipe was marked closed, but the upper layer was not.  So it was remotely initiated.  Or at the bottom side of the transport layer.

**Comment by gdamore** [comment]
Spent quite a bit of time instrumenting this.   For reasons I don't understand, it would appear that sometimes we get a POLLHUP event from the epoll implementation.  This seems like it should never occur on a newly minted socket, and yet we are seeing it.  I've been trying to tie this to a disconnect of the peer pipe, but have been unable to isolate a closing peer.  I'm starting to think that if we wind up polling on a pipe too swiftly after doing connect() that we can see this error occur.  To be honest, it feels like a bug to me.  We're not seeing this on any platform except LInux, and specifically Ubuntu 18.04.

Experimentally I basically disabled the handling for POLLHUP, so that we treat it as a POLLOUT instead of a hang up, which forces us to try to initiate another write (if one is pending).  This seems to work so far, but I want to let the test run a bit longer to be sure.

**Comment by tsunami650** [comment]
I've run into some problems with epoll on linux that may be related to this change.

I'm building some sample applications learning to use nng, coming from a traditional sockets background. In my test applications, one program listens on a tcp port with the publish protocol. Another dials the address that the first one is listening on. Each application runs on a different physical linux machine (dialer is Ubuntu 14.04, listener is Ubuntu 16.04).  The listen/publish instance sends a message once a second. The dial/subscribe instance simply prints it to stdout. I noticed sometimes, when stopping the listener and then starting it back up again a few seconds later, the dialer instance would not ever successfully reconnect.  

To rule out my use (or misuse) of the library, I switched to using `nngcat` to try and replicate the problem. Provided that the dialer/subscriber is on a different machine from the listener/publisher, I can pretty quickly replicate the issue. If I rapidly stop and then start back up the listener (with a 1-3 second pause inbetween stop and start), occasionally the dialer instance will think it connected at the transport layer, when actually the listener has been shutdown. I verified that this is the case by instrumenting `platform/posix/posix_tcpdial.c` in the function `tcp_dialer_cb()`. 

Right after I issue a SIGINT to the listener/publisher instance, the dialer/subscriber will queue a redial attempt, and in the `tcp_dialer_cb()` function, `getsockopt()` is called to get the `SO_ERROR` return value for the aio. Usually the `rv` error code will be `NNG_ECONNREFUSED` (6), but every once in a while it will be a success (0).  This is before the listener/publisher has been started back up again. At this point, if the listener is started, the dialer never connects to it since it believes it has already successfully connected. The transport socket is now stuck in a stale state, where no messages arrive since the nng sock appears to be connected to a dead underlying tcp socket at the transport layer.

As a test, I added `EPOLLHUP` back in to `src/platform/posix/posix_pollq_epoll.c` in the event mask before `epoll_ctl()`, and included it in the callback portion whitelist of bits (from `EPOLLIN | EPOLLOUT | EPOLLERR` to also include `EPOLLHUP`). In each case where the error reproduced, if `getsockopt()` had 0 as the return value code, I added a check to see of `POLLHUP` was set in the event mask.  Most times the event mask would not have `POLLHUP` set, but everytime I triggered the error case, it was.  In the case of `rv == 0 && ev & POLLHUP`, I set `rv = ECONNRESET;` and could no longer repro the problem.  

I am not sure if this is the proper fix, or if this change would break other behavior in some way that I haven't yet encountered. If you have trouble reproducing the reconnect failure on linux, though, I am happy to help in any way I can.  Library built from this commit c3e062661388f70386d6766e3ce648030af340ee
