### ISSUE TITLE
Async Req Server: Question

### ISSUE THREAD

**Issue by iyer-arvind** [nanomsg/nng#695]
Hi,
Just starting out with nng, I created a server which `listens` with a `req` socket. I wanted this to be async, and used `ctx` + `aio`. There are 8 parallel contexts listening to request.

The result of the following code is that all 8 request simultaneously even when there is a single client connecting. 

Is the async + req + listen possible, and i am making a mistake somewhere?

``` c++
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <nng/nng.h>
#include <nng/protocol/reqrep0/req.h>
#include <nng/supplemental/util/platform.h>



void
fatal(const char *func, int rv)
{
	fprintf(stderr, "%s: %s\n", func, nng_strerror(rv));
	exit(1);
}
typedef enum {HANDSHAKE = 0, QUERY, REPLY, RESPONSE, EXIT} State;

typedef struct s_rep_data_t
{
  nng_ctx ctx;
  int idx;
  State state;
  void *payload;
} StateData;


void state_transit(void *_ptr)
{
  StateData *stateData = (StateData*) _ptr;
  
  State state = stateData->state;
  int idx = stateData->idx;
  int ctx = stateData->ctx.id;
  switch(state)
  {
    case HANDSHAKE:
      {
        printf("%d, %d: HANDSHAKE\n", idx, ctx);
        stateData -> state = QUERY;
        
        nng_msg *msg;
        nng_msg_alloc(&msg, 0);
        nng_msg_append(msg, "HELLO", 5);

        nng_aio *aio;
        nng_aio_alloc(&aio, &state_transit, stateData);

        nng_aio_set_msg(aio, msg);
        nng_ctx_send(stateData->ctx, aio);
      }
      break;

    case QUERY:
      {
        printf("%d,%d: QUERY\n", idx, ctx);
        stateData -> state = REPLY;
        nng_aio *aio;
        nng_aio_alloc(&aio, &state_transit, stateData);
        nng_ctx_recv(stateData->ctx, aio);
      }
      break;

    case REPLY:
      {
        printf("%d,%d: REPLY\n", idx, ctx);
        stateData -> state = RESPONSE;

        nng_msg *msg;
        nng_msg_alloc(&msg, 0);
        nng_msg_append(msg, "RECVD", 5);

        nng_aio *aio;
        nng_aio_alloc(&aio, &state_transit, stateData);

        nng_aio_set_msg(aio, msg);
        nng_ctx_send(stateData->ctx, aio);
      }
      break;

    case RESPONSE:
      {
        printf("%d,%d: RESPONSE\n", idx, ctx);
        stateData -> state = EXIT;
        nng_aio *aio;
        nng_aio_alloc(&aio, &state_transit, stateData);
        nng_ctx_recv(stateData->ctx, aio);
      }
      break;

    case EXIT:
      {
        printf("%d,%d: EXIT\n", idx, ctx);
      }
      break;
  }; 
}

int main()
{
  nng_socket sock;
  nng_req0_open(&sock);
  int rv;
	if ((rv = nng_listen(sock, "tcp://127.0.0.1:12300", NULL, 0)) != 0)
			fatal("nng_listen", rv);

  
  for(int i=0; i< 8; i++)
  {
    StateData *stateData = nng_alloc(sizeof(stateData));
    stateData->state = HANDSHAKE;
    stateData->idx = i;
    nng_ctx_open(&stateData->ctx, sock);
    state_transit(stateData);
    printf(".\n");
  }

	for (;;) {
		nng_msleep(3600000); // neither pause() nor sleep() portable
	}
  nng_close(sock);
  return 0;
}

```

P.S. Could someone point me out a mailing list where I could ask such doubts to the community?

**Comment by gdamore** [comment]
Sorry, this fell between the cracks.  Let me look now and get back to you.  (You can also use our gitter chat, or the nanomsg@freelists.org mailing list.)

**Comment by gdamore** [comment]
So there are a few things wrong here.

One is that you're using a REQ server to attempt to send requests to the server.  Of course, they are all going to run in parallel, because they are independent.  Normally you want to use contexts with REQ when you have other discrete needs for parallelism.  For example, if you are using REQ to talk to a database server, but each req is mapped to a single REST API query -- so you don't start issuing requests on a context until some other event happens.

(In the example above, the incoming REST call would cause a context to be selected, or created perhaps, which would then be used to service the database inquiries related to that REST client.  Other REST API clients would wind up utilizing a different context.)

The other problems you have are leaking aios (badly) -- you can just reuse the same aio in your state structure if you like -- with a state machine like you have this would actually be the best design.

Also, you need to check for result codes with nng_aio_result() -- the callback may be called even if the operation didn't completely successfully.

Structurally, you need to determine whether multiple contexts makes sense for your application.  As i outlined, there are designs where it does.  Your program doesn't do that though -- it just runs 8 requests in parallel triggered by nothing special.

(Note that REP is different here -- a REP socket gates behind a incoming request, so it is inherently a bit better in that regard, since an external event triggers it's start.)

**Comment by iyer-arvind** [comment]
Thanks a lot for the response!
I will have a closer look.
