### ISSUE TITLE
How to implement work queue server?

### ISSUE THREAD

**Issue by lkesteloot** [nanomsg/nng#728]
I'm implementing a work queue server using req/rep. It's backwards from normal req/rep because it's the server that sends the requests and the workers (clients) who respond.

I can't get this to work with nng. All workers end up on the same socket, and there's no way for the server to specify which worker to send a request to, or even notice that a worker has connected or disconnected.

I'm looking for a more traditional socket approach where `accept()` returns a new descriptor for that connection. I'd like for nng's listener to return a new socket that I can set up with req/rep. I looked into the pair protocol but it doesn't seem to support async (`nng_ctx_open` fails).

**Comment by gdamore** [comment]
So the point of req/rep (and to some extent NNG) is that it does this for you.  You can of course open multiple NNG sockets, but that sort of defeats the purpose.

In theory an NNG REQ socket should choose one of its REP peers automatically.  Ideally it does this in something approaching round-robin fashion. 

One thing you might consider is a paradigm where your client workers use a REQ socket, but their request is essentially "give me a job please", and then sometime later, "I'm done with the job.  This means building your logic on top of the underlying REQ/REP, but it should work.

When you want to select *which* client gets the work, that's something that NNG REQ/REP isn't good at, and you'll really want separate NNG sockets for that.

pair *does* support async, but it does not support nng_ctx_open -- because it's a totally stateless protocol.  As a stateless protocol, there is no need for contexts (no point), and you can just use the single socket with nng_recv_aio nng_send_aio.

**Comment by patrickkh7788** [comment]
stateless  socket with nng_ctx can be used as multiplex stream, like http2.

for example I can pass 2 context stream from one stateless socket handle,  allow 2 isolated login share one connection.

**Comment by gdamore** [comment]
Being a stream means that you need to have at least enough state to
separate out the messages from different streams. There is none of that at
the protocol level for pair.

**Comment by lkesteloot** [comment]
I could have the workers send the requests, but I still have the problem of the server not knowing when a worker disconnects part-way through doing some work. Sounds like I really need a new high-level nng protocol family for work queues. It would allow the server to know when a worker connects and disconnects, would allow it to send requests to specific workers, and have the workers send responses. Without this, I'm not sure that I want to (or can) shoehorn nng's current protocols into that pattern.

**Comment by gdamore** [comment]
Nng does have port events which you can use for this. But directing
requests to specific workers is just not part of the current architecture.

**Comment by lkesteloot** [comment]
Okay thank you!

**Comment by c0ffymachyne** [comment]
reimplement it so that the thread workers work like that : So the point of req/rep (and to some extent NNG) is that it does this for you. You can of course open multiple NNG sockets, but that sort of defeats the purpose.

In theory an NNG REQ socket should choose one of its REP peers automatically. Ideally it does this in something approaching round-robin fashion.

One thing you might consider is a paradigm where your client workers use a REQ socket, but their request is essentially "give me a job please", and then sometime later, "I'm done with the job. This means building your logic on top of the underlying REQ/REP, but it should work.

When you want to select which client gets the work, that's something that NNG REQ/REP isn't good at, and you'll really want separate NNG sockets for that.

pair does support async, but it does not support nng_ctx_open -- because it's a totally stateless protocol. As a stateless protocol, there is no need for contexts (no point), and you can just use the single socket with nng_recv_aio nng_send_aio
