### ISSUE TITLE
Question about mutex in aio callback function

### ISSUE THREAD

**Issue by bill1600** [nanomsg/nng#753]
The doc says not to block in a callback function.

But if the callback function, which I expect to execute in a different thread from the one that initiated the I/O, needs to update shared data, like putting received data on a queue for instance, then it would need to use a mutex to do the enqueuing.  This seems reasonable.  But will that usage of a mutex cause bad things to happen ?

**Comment by gdamore** [comment]
It really depends on what might be holding the mutex.  If the mutex might be held by another blocking function, then this would cause this function to “block”, which would gum up the works.

To give you a more concrete example:

If you have code that acquires the mutex, checks to see if there is room on the queue, then either queues (if there is), or drops the message, and then finally releases the mutex, and if the thing that empty the queue just holds the mutex long enough to get an item from the queue (without blocking), then it’s all good.

Conversely, if your callback acquires the mutex, and then waits for there to be room, then this is bad because the worker thread will be blocked until then, and that can prevent new work from being processed.  If that new work is required for your callback to make forward progress, then this can actually lead to a deadlock, rather than just a “stall”.

Another way to think of it is like this: will anything that holds that lock have to wait (or take a long time to run) before releasing the lock?  If the answer to that is *no*, then you’re fine.

Also remember that condition variables do release the lock, and can be very helpful in these situations.

 - Garrett

**Comment by gdamore** [comment]
I believe I've answered the question.  If you feel otherwise, please feel free to reopen this issue and I'll try to clarify further.
