### ISSUE TITLE
Pub/Sub very slow compared with nanomsg

### ISSUE THREAD

**Issue by igiagkiozis** [nanomsg/nng#762]
## NNG & Platform details.
nng version 1.0.1 - Fedora 28 - C++

I used the pub/sub pattern and measured peak message throughput of 35k messages per second with an average of 20k messages per second. Using exactly the same code, only replacing the nng specific code with nanomsg I get about 1M messages per second which is not brilliant either but I have made no attempts at optimization so that's fine.

I was very surprised by the difference in performance, am I missing something obvious here?

P.S. I just used the code from the examples both for nanomsg and nng.

**Comment by gdamore** [comment]
I’ll have to look — how are you measuring, and which transport are you using?

  - Garrett

**Comment by igiagkiozis** [comment]
I'm using the IPC transport - regarding the measurement its the following on the receiving end: 
`    Subscriber sub{"master"};
    std::cout << "In DataPersistence System" << std::endl;
    auto start_time = high_resolution_clock::now();
    int64_t count = 0;
    while(true) {
      auto msg = sub.read();
      if(!msg.empty())
        ++count;
      if((count & 0x000000000000FFFF) == 0xFFFF) {
        auto end_time        = high_resolution_clock::now();
        auto elapsed_seconds = duration_cast<duration<double>>(end_time - start_time);
        elapsed_seconds.count();
        auto messages_per_sec = count / elapsed_seconds.count();
        std::cout << "msgs/sec: " << messages_per_sec << std::endl;
      }
    }`

**Comment by gdamore** [comment]
So Pub/Sub is horrible for performance analysis, because it can drop messages due to flow control.  I’m wondering if that is what we’re seeing.  Legacy nanomsg had a different approach where it might actually block the sender, where NNG refuses to do so, but consequently the messages might not be received if the producer is pushing too quickly.

What this may mean is that the sender is spinning on “send()” fair more quickly (may be it thinks it has sent some much much larger number of messages), but the time taken to discard rather than block is killing the ultimate final throughput.

I also don’t recommend using Pub/Sub in high throughput scenarios.  (It is fine if your main concern is latency, but not for throughput.)

If you want to measure performance, please try using PAIR or (if you want round trip times) REQ/REP.

 - Garrett

**Comment by igiagkiozis** [comment]
I know that's not what you suggested but just to clarify, I'm actually blocking on the receiving end. 

Will give the PAIR a go but for my application the PUB/SUB seems to be the natural option. In essence I have a ticker plant and I need to distribute the data to several consumers (persistence, operational data store, event handlers etc).

Will post an update once I have some results.

**Comment by gdamore** [comment]
The issue is on the sending side. If the sender is discarding messages
because of flow control (such as the receiver not being able to keep up)
you may get a very distorted picture.

The pub sub pattern is not meant for high throughput situations.

Having said that I will have a look at this because your numbers seem low
to me.

One thing you might try is to inject a one microsecond delay between sends.
That will limit you to at most 1M msgs / sec but it may ease back enough on
the pressure for your sub to catch up.

Also please make sure you are either using two systems or have multiple
cores. On a single core VM for example the publisher may just burn the
entire core trying to push and discarding messages completely starving the
subscriber.

**Comment by gdamore** [comment]
It's possible also, as I think about this, that we have some scaling opportunities we are missing in the underlying poller.  Right now we have exactly one poller doing all socket operations. 

I haven't had time to measure things here, but I need to do so.

Would be great if you had a C (rather than C++) test case.

**Comment by gdamore** [comment]
With NNG 1.1.0, on my macOS box, I'm seeing similar figures of around 30k msg/sec on average.  With a sender that is simply discarding messages I see thousands of message discards too.  (in one case like 8k messages dropped, because the sender was pumping faster than my naive test program could keep up.  My dummy sender sends an incrementing message ID, and my receiver looks for gaps.)

Again this is on macOS, so YMMV.  (I've found Linux usually out performs macOS for networking stuff.)

**Comment by gdamore** [comment]
My test program is at https://gist.github.com/gdamore/b36c9dfcb000891eb2c993fde7b6178a

**Comment by gdamore** [comment]
At some point I need to break out a profiler and look at this properly, especially on a Linux box.  The macOS threading architecture is really really bad (locks are super painful) so that the stuff we are doing to scale out to multiple threads may unduly impact single threaded performance.

**Comment by igiagkiozis** [comment]
I'll have some time this weekend and will check on Linux; will let you know what I find.

**Comment by dtaht** [comment]
This is one of those places where I'd like to try applying the fq_codel algorithm (RFC8290) instead of "flow control" per se'. Dropping from head, trying to limit queue depth, doing load balancing across destinations...

**Comment by gdamore** [comment]
I've just pushed a rather significant rework of the Sub pattern which should --- I hope -- provide better performance.  This is in the "subperf" branch for now.  It also supports contexts.

There are other areas for enhancement here.  We need to make the receive queue tunable, and we should really replace the dumb subscription algorithm with a real patricia tree.  That's on my list of things to do.

**Comment by gdamore** [comment]
"subperf2" includes fixes for pub, and a new utility called pubdrop (in the perf directory).  This branch Is just about ready for integration -- and I've proven to myself that it runs much much more quickly than the old code.  Unfortunately, its super easy to get message drops by having a slow receiver, and making everything faster just exacerbates this.

If you're using many subscriptions, you'll also run into a nasty performance problem in the subscriber, as it uses an *extremely* naive filter.  I will be replacing it with a proper patricia tree before too long.

**Comment by gdamore** [comment]
The other thing is that a single threaded sender using NNG will almost certainly never match nanomsg.  That's because for this most trivial case nanomsg does quite a lot less, as it does not try to scale across CPUs. The horizontal scalability of nanomsg is rather poor.  It also doesn't work well if you add an event loop using the poll or select API, because it has to do several extra system calls.  In real-world workloads I expect NNG to outperform nanomsg.  Trivial benchmarks penalize NNG, but reward nanomsg.

**Comment by gdamore** [comment]
The commit I plan to integrate does help this substantially, but not completely.  We also need to address #899 as well as fix some things in the underlying poller.

Ultimately, for certain limited use cases, we will probably never beat out nanomsg.  But for real world tests at scale, we should.
