### ISSUE TITLE
How to limit worker threads

### ISSUE THREAD

**Issue by bill1600** [nanomsg/nng#769]
Is there a way to limit the number of worker threads that NNG uses?

We have some execution environments with very limited memory resources.

We are trying to limit or reduce the number of our own threads, and this is hard
enough without NNG going in the opposite direction.

**Comment by gdamore** [comment]
NNG creates a relatively small number of threads:

1) timer thread -- just one that wakes periodically to handle background timing stuff.
2) expiration thread - this is used for expiring aios (someday we will collapse this and 1 above)
3) reap thread - used for reaping objects after they are destroyed (to break deadlocks)
4) resolver threads - used for DNS lookups - defaults to 4
5) pollq (epoll, kqueue, select) worker thread - currently just 1
6) taskq threads - used for processing completion events - NCPU * 2 threads
7) ZeroTier thread - only if ZT is configured

Today these are not readily tunable.  Arguably the pollq worker threads should scale to the number of cores, and maybe the resolver threads as well.  You could reasonably reduce the resolver thread (item 4 above) to just one thread, but then DNS lookups will all block for that one thread.  (If you're only using IP addresses, it might be possible to eliminate that thread entirely.)  This will be located in the src/platform/posix/posix_resolv_gai.c code.

You could also change the code for taskq threads to just use a fixed count -- but I strongly recommend at least 2 of these.  There may be livelock conditions that can arise with just 1.  That is driven in src/core/taskq.c

The other threads are required.  Today a single core system will result in 10 distinct threads.  (11 if you use ZeroTier).  Easy code alterations suggested above could reduce this to 7 (sparing you 3 threads).

Having said all this, these threads do not normally contend for CPU.  So mostly they just sit around waiting until they have work to do.

However, if you have *memory* constraints, then it might be that the stack size is an issue.  The default Linux stack size is rather large.  You *can* reduce the stack size pretty easily -- I see no reason that NNG would not work with stacks as small as 8K.  You would need to change the thread creation code to configure a suitable stack size.  I just made changes to do this mostly to increase stack sizes because some application code wants big stacks (in their user callbacks).

You could alter the code src/platform/posix/posix_thread.c to allocate a *small* stack size pretty easily.  In fact, if you're willing to do this for *all* of your stacks, you can do it based on ulimit, and configuring the library with NNG_SETSTACKSIZE at CMake configuration time.

All of this assumes that you have a reasonable POSIX platform that you're working on.  If it is something else, let me know.

I'd be happy to accept PRs to make any of these things that should be more tunable be so.  I'd also be willing to do the work to do so myself, although if this is a commercial venture I'd recommend doing so as a supported / sponsored effort -- let me know if you want to pursue that.

Thanks.

**Comment by gdamore** [comment]
Actually, I'm thinking that for the threads that are used exclusively internally -- the reap, timer, and resolver threads, I can probably go ahead and proactively set the stack size small. There is no reason to allocate a stack larger than 8k or the platform minimum stack size (whichever is larger).

**Comment by gdamore** [comment]
That's probably true for the pollq stack as well.  I just have to be very careful that I never call back into user code with a tiny stack - that code generally can't cope with it.  And btw, C++ code tends to be horrible here -- the ZeroTier code blows through an 80k stack pretty easily for example.

**Comment by mjgigli** [comment]
Just wanted to leave a note here for others who come across this and want to know how to limit the DNS resolver and taskq threads. #769 introduces 2 new cmake variables that can be used to set the number of DNS resolver and taskq threads, respectively:

```
cmake -DNNG_RESOLV_CONCURRENCY=1 -DNNG_NUM_TASKQ_THREADS=2 ..
```

**Comment by pfeatherstone** [comment]
I tried adding those two options in cmake-gui and it seems to have no affect
