### ISSUE TITLE
sockimpl.h and posix_aio.h missing in build system

### ISSUE THREAD

**Issue by woodstock23** [nanomsg/nng#800]
## NNG & Platform details.
nng 1.1.1
issue is platform & compiler independent

## Expected Behavior
All source code files are managed by the build system

## Actual Behavior
At least two files are missing in the build system

## Steps to Reproduce
Try to find src/core/sockimpl.h and src/platform/posix/posix_aio.h in any CMakeList.txt file.

## Comment
Maybe the files are missing on purpose, but I can't think of a good reason for that.
I use my own macros to avoid this situation. They scan the source directories for all files, compare them with the files listed in the CMakeList.txt, and complain if they find unknown files. I am happy to provide these macros if you are interested.

**Comment by gdamore** [comment]
No, they were omitted by mistake.  The omission should be harmless, because they don't actually get delivered into the system -- they are rather internal headers.  The only concern would be that updates to these headers might not trigger a build rule to be updated, meaning you might have to touch some other file or do a make clean (or the moral equivalent) to get a proper build after changing either of these files.

**Comment by woodstock23** [comment]
Yep, harmless for the build. There is also another minor inconvenience: the files might not show up in the project in an IDE, e.g. Visual Studio.
