### ISSUE TITLE
More Information on "no blocking allowed"

### ISSUE THREAD

**Issue by athei** [nanomsg/nng#856]
I am using nng in a server application where sometimes I need to take a lock to access some data structure. Of course this also happens in a callback because everything happens in callbacks in a server style application (using req protocol).

How should we do synchronization between concurrent callbacks if not with blocking? And also what is the problem with blocking? Does it introduce deadlocks? If so: why?

**Comment by gdamore** [comment]
You can take the lock in a callback.  What you need to do is ensure that nothing else that takes the lock also blocks while holding the lock.  (Alternatively you can use a try-lock primitive, although at that point you need to use your own locking primitive APIs, because I've not exposed those in the NNG API.)

The reason blocking is a problem is that there are a finite number of worker threads.  If your call blocks, then that stops the worker thread.  If this were to happen just once or twice it would probably be fine, but if you also have code to wait for the callback or aio to complete, that will *also* block.  Eventually, as enough threads get blocked, you run out of worker threads and everything grinds to a stop.

The design is fundamentally that your callbacks just don't "block".  ("Blocking" does not mean waiting for a lock, unless the holder of the lock is blocked -- e.g. if your application holds the lock while waiting  for user input -- that would be an unsafe lock to acquire in a callback.

Well designed applications usually have little or no need to hold locks while doing blocking operations.

**Comment by gdamore** [comment]
I hope I've answered this.  Please feel free to follow up with questions on either our mailing list -- nanomsg@freelists.org -- or our gitter chat.
