### ISSUE TITLE
NNG_OPT_REQ_RESENDTIME does not honor NNG_DURATION_INFINITE

### ISSUE THREAD

**Issue by athei** [nanomsg/nng#857]
I am trying to disable the re-transmit functionality of the req protocol. I use reliable transports and don't want messages to be received multiple times.

I use this on my context
`nng_ctx_setopt_ms(req_ctx.ctx, NNG_OPT_REQ_RESENDTIME, NNG_DURATION_INFINITE);`

## NNG & Platform details.
v1.1.0 on Linux

## Expected Behavior
Re-transmits are effectively disabled.

## Actual Behavior
Messages are send multiple times because `NNG_OPT_REQ_RESENDTIME` is interpreted as a interval of -1 which schedules the re-transmit immediately:
```
// Schedule a resubmit timer.  We only do this if we got
// a pipe to send to.  Otherwise, we should get handled
// the next time that the sendq is run.
nni_timer_schedule(&ctx->timer, nni_clock() + ctx->retry);
```

## Steps to Reproduce
Not really necessary. Already pointed out what the problem is.

**Comment by gdamore** [comment]
There really isn't such a thing as a "reliable transport" - the only way to ensure true reliability is to get the ack back from the peer -- without an ack back, the protocol will pretty much stall forever if your request is dropped.  (There are quite a few failure modes that don't require a connected TCP transport to drop the message -- for example the TCP connection itself can be dropped, or the peer may go offline due to a reboot, or even the application can crash after the message has been received by the peer kernel, but before the peer has a chance to act on it.)

If retransmits cause you grief, probably it's because your protocol is not idempotent.  Requests *must* be idempotent, or the results may be "surprising".

Having said that, I agree that the handling of NNG_DURATION_INFINITE is incorrect, and I'll fix it.

**Comment by athei** [comment]
I find idempotence a demanding requirement. I would rather take the imperfect reliability of just TCP and deal with a failure.

**Comment by gdamore** [comment]
If you're not wanting the automatic retries... then probably you aren't really needing REQ/REP.  Maybe this is the wrong pattern for you to use?
