### ISSUE TITLE
[request] socket activation

### ISSUE THREAD

**Issue by gregorburger** [nanomsg/nng#863]
consider an application that consists of multiple processes, on a single machine, that communicate via nng ipc. each processes could read/write from/to multiple sockets. Starting that system is currently very painful and needs extra code just for startup and could also cause deadlocks. 

Socket activation would solve the problem, it is used in systemd/inetd to make application startup parallel without sequentially starting application that need sockets from other applications. (see [0])

It would be nice if nng would provide a socket constructor / set_sock_opt where we can pass a already "activated" socket descriptor. 

ZeroMQ does it using  zmq_setsockopt(..., ZMQ_USE_FD, ...) [1]

[0] http://0pointer.de/blog/projects/socket-activation.html
[1] https://github.com/zeromq/libzmq/blob/3683a96fcbf25c4bc04ac4b002a1b1550db99767/tests/test_use_fd_ipc.cpp

**Comment by gdamore** [comment]
From what I can see, the main benefit of socket activation is not having to keep a daemon process around.  (There is no *ordering* problem with NNG per se, since dialers will just keep retrying behind the cover -- this is the nature of NNG's self-healing design.)  On modern systems, this is probably of little real value, since an idle process will probably be paged out under memory pressure, consuming only minor resources (a set of page table entries that are swapped out, and a slot in the process table).  Of course, if there is no memory pressure, it may sit around consuming memory, but with no pressure this is also harmless.

NNG is portable systems where network connections might not be file descriptors, so any design there would need to be carefully thought out -- for UNIX and Linux, socket descriptors would work.

To do this "right", I'd really want to rethink (and have been considering this anyway) how dialers and listeners work, and expose the ability to create a pipe from an underlying descriptor.  However, this feels really fraught to get to work portably with the underlying platform porting layer.

If someone wanted to take a stab at a PR for this, I could take a look.  Otherwise I probably won't work on it unless someone backs the request up with commercial sponsorship -- I just am having a difficult time seeing enough justification for it on my own.

Note that for non NNG programs, based around traditional connect/accept semantics, and without any underlying reconnection strategy, this would make a lot more sense.  That's not NNG.

**Comment by gdamore** [comment]
There *is* now a framework based on socketpair (see the socket:// transport).  You could give it a TCP socket and that would work.  At present it won't work for an IPC socket because we use the TCP messaging format.  (For obscure historical reasons, nanomsg uses a different wire format when speaking over UNIX domain sockets that when speaking over TCP. I chose the simpler TCP format for socket:// transport.)

I'm not sure if this solves the problem for the poster -- but it certainly can be the start of a solution.

**Comment by gdamore** [comment]
So reading more about this, it seems like socket activation is a little different, because instead of passing the accepted socket, we are passed the server socket that we can perform accept on().  Basically sort of a deferred startup.

My idea is to use something similar to what we did for socketpair, but instead use an option like NNG_OPTION_LISTEN_FD... this should be passed to a listener that has not yet been started. 

This would then skip the bind() step, and just use that FD directly.

If multiple FDs are needed, e.g. for different IP addresses or different protocols, then they should each have their own listener.

It is possible that we could allow listeners to be created with a magical tcp:// url without any parameters, which would mean that they could *only* be used with socket activation type connections.

One final idea, we might want to extend the notion of connected sockets as well, so that we could accept a FD that was already connected.  This could be useful for inetd style configuration.

I don't *think* Windows has anything like this, but it would be easy to extend this to HANDLEs as well as file descriptors.

We would want to support this for TLS+TCP as well.

I don't see how this requires more than a day of effort to implement -- probably only a few hours.  I'll try to include it for NNG 1.8.

**Comment by gdamore** [comment]
So I've implemented this as an option that can be called on a listener that has not been started yet.  You call `nng_listener_set_int(listener, NNG_OPT_LISTEN_FD, fd);`  It can be used with TCP, TLS, and IPC listeners.  (The latter only on POSIX, the others can be used on any system.)

Using the systemd API to get those file descriptors is a task for the application author -- but this change at least makes it possible to build solutions like this.

I'll probably follow up with a version that can be used for inetd style systems too, shortly.
