### ISSUE TITLE
WebSocket ephemeral port cannot be reused

### ISSUE THREAD

**Issue by jonthn** [nanomsg/nng#907]
## NNG & Platform details.

nng (HEAD 6f25aa48a2ff0033073d6ee541748eccc685727d )
macOS 10.14.3

## Expected Behavior

Listening on WebSocket with a first URL using port `0` to let the system select an available port, and then being able to retrieve and use the same port for another url.

1. Listen to `ws://*:0/foo` (let's say the system allocated TCP port 23856)
2. Being able to listen to `ws://*:23856/bar`

## Actual Behavior

Currently the library can select a port automatically and also the API is sufficient to retrieve this port.
But the next

## Steps to Reproduce

By applying this diff to test program `ws` you should be able to reproduce this behaviour

```diff
diff --git i/tests/ws.c w/tests/ws.c
index e5cc8ba5..cb53fa40 100644
--- i/tests/ws.c
+++ w/tests/ws.c
@@ -20,6 +20,8 @@
 #include "stubs.h"
 #include "trantest.h"
 
+#include <err.h>
+
 static int
 check_props_v4(nng_msg *msg)
 {
@@ -155,5 +157,32 @@ TestMain("WebSocket Transport", {
 		So(nng_dial(s2, "ws://127.0.0.1:5599/one", NULL, 0) == 0);
 	});
 
+	Convey("Random port works and next listen with same port also", {
+		nng_socket s1;
+		nng_socket s2;
+		nng_listener l1;
+		nng_sockaddr s_addr1;
+		int port = 0;
+		char ws_url[1024] = {0};
+		So(nng_pair_open(&s1) == 0);
+		So(nng_pair_open(&s2) == 0);
+		Reset({
+			nng_close(s1);
+			nng_close(s2);
+		});
+		So(nng_listen(s1, "ws://*:0/one", &l1, 0) == 0);
+		So(nng_listener_getopt_sockaddr(l1, NNG_OPT_LOCADDR, &s_addr1) == 0);
+		// Assume we only encounter IPv4 and IPv6
+		if (NNG_AF_INET == s_addr1.s_family) {
+			port = ntohs(s_addr1.s_in.sa_port);
+		} else if (NNG_AF_INET6 == s_addr1.s_family) {
+			port = ntohs(s_addr1.s_in6.sa_port);
+		}
+		snprintf(ws_url, 1023, "ws://*:%d/two", port);
+		int ret = nng_listen(s2, ws_url, NULL, 0);
+		warnx("nng_listen(... %s ....) returned %d (%s)", ws_url, ret, nng_strerror(ret));
+		So(ret == 0);
+	});
+
 	nng_fini();
 })

```

### Output after applying the diff

```
./tests/ws
ws: nng_listen(... ws://*:61788/two ....) returned 10 (Address in use)


Failures:

  * Assertion Failed (Random port works and next listen with same port also)
  File: nng-git/tests/ws.c
  Line: 184
  Test: ret == 0
  
ok      ./tests/ws
```

**Comment by jonthn** [comment]
I forgot to mention, that using a fixed port number for the first listen, doesn't show the problem or same behaviour

**Comment by gdamore** [comment]
This makes perfect sense.  It may be a simple fix. If you use the wildcard again you will get another ephemeral port and it should work. Reuse of ephemeral ports won't work without further work. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jonathan Buschmann <notifications@github.com> Date: 3/11/19  6:48 PM  (GMT-08:00) To: nanomsg/nng <nng@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [nanomsg/nng] WebSocket and ephemeral port, subsequent call with same port fails with EADDRINUSE (#907) NNG & Platform details.
nng (HEAD 6f25aa4 )
macOS 10.14.3
Expected Behavior
Listening on WebSocket with a first URL using port 0 to let the system select an available port, and then being able to retrieve and use the same port for another url.

Listen to ws://*:0/foo (let's say the system allocated TCP port 23856)
Being able to listen to ws://*:23856/bar

Actual Behavior
Currently the library can select a port automatically and also the API is sufficient to retrieve this port.
But the next
Steps to Reproduce
By applying this diff to test program ws you should be able to reproduce this behaviour
diff --git i/tests/ws.c w/tests/ws.c
index e5cc8ba5..cb53fa40 100644
--- i/tests/ws.c
+++ w/tests/ws.c
@@ -20,6 +20,8 @@
 #include "stubs.h"
 #include "trantest.h"
 
+#include <err.h>
+
 static int
 check_props_v4(nng_msg *msg)
 {
@@ -155,5 +157,32 @@ TestMain("WebSocket Transport", {
 		So(nng_dial(s2, "ws://127.0.0.1:5599/one", NULL, 0) == 0);
 	});
 
+	Convey("Random port works and next listen with same port also", {
+		nng_socket s1;
+		nng_socket s2;
+		nng_listener l1;
+		nng_sockaddr s_addr1;
+		int port = 0;
+		char ws_url[1024] = {0};
+		So(nng_pair_open(&s1) == 0);
+		So(nng_pair_open(&s2) == 0);
+		Reset({
+			nng_close(s1);
+			nng_close(s2);
+		});
+		So(nng_listen(s1, "ws://*:0/one", &l1, 0) == 0);
+		So(nng_listener_getopt_sockaddr(l1, NNG_OPT_LOCADDR, &s_addr1) == 0);
+		// Assume we only encounter IPv4 and IPv6
+		if (NNG_AF_INET == s_addr1.s_family) {
+			port = ntohs(s_addr1.s_in.sa_port);
+		} else if (NNG_AF_INET6 == s_addr1.s_family) {
+			port = ntohs(s_addr1.s_in6.sa_port);
+		}
+		snprintf(ws_url, 1023, "ws://*:%d/two", port);
+		int ret = nng_listen(s2, ws_url, NULL, 0);
+		warnx("nng_listen(... %s ....) returned %d (%s)", ws_url, ret, nng_strerror(ret));
+		So(ret == 0);
+	});
+
 	nng_fini();
 })

Output after applying the diff
./tests/ws
ws: nng_listen(... ws://*:61788/two ....) returned 10 (Address in use)


Failures:

  * Assertion Failed (Random port works and next listen with same port also)
  File: nng-git/tests/ws.c
  Line: 184
  Test: ret == 0
  
ok      ./tests/ws


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nanomsg/nng","title":"nanomsg/nng","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nanomsg/nng"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"WebSocket and ephemeral port, subsequent call with same port fails with EADDRINUSE (#907)"}],"action":{"name":"View Issue","url":"https://github.com/nanomsg/nng/issues/907"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nanomsg/nng/issues/907",
"url": "https://github.com/nanomsg/nng/issues/907",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jonthn** [comment]
> This makes perfect sense.  It may be a simple fix. If you use the wildcard again you will get another ephemeral port and it should work. Reuse of ephemeral ports won't work without further work.

I used the term "ephemeral port" but my goal is to just obtain an available random port that I will use in this application for multiple URL.
And I would add it's a bit disturbing that a URL which is just a string when set to a fix port it behaves in one way and later by getting a random port and building a second URL with that number you cannot achieve the same. Both doesn't give you the same result I would have guessed it worked given the fact `nng` is a _bit_ higher than BSD  socket

**Comment by gdamore** [comment]
I understand what you want. It isn't unreasonable. It just won't work without a bit more effort in nng because of the simplicity of the string matching algorithm in nng. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Jonathan Buschmann <notifications@github.com> Date: 3/11/19  8:09 PM  (GMT-08:00) To: nanomsg/nng <nng@noreply.github.com> Cc: gdamore <garrett@damore.org>, Comment <comment@noreply.github.com> Subject: Re: [nanomsg/nng] WebSocket and ephemeral port, subsequent call with same port fails with EADDRINUSE (#907) 
This makes perfect sense.  It may be a simple fix. If you use the wildcard again you will get another ephemeral port and it should work. Reuse of ephemeral ports won't work without further work.

I used the term "ephemeral port" but my goal is to just obtain an available random port that I will use in this application for multiple URL.
And I would add it's a bit disturbing that a URL which is just a string when set to a fix port it behaves in one way and later by getting a random port and building a second URL with that number you cannot achieve the same. Both doesn't give you the same result I would have guessed it worked given the fact nng is a bit higher than BSD  socket

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nanomsg/nng","title":"nanomsg/nng","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nanomsg/nng"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jonthn in #907: \u003e This makes perfect sense.  It may be a simple fix. If you use the wildcard again you will get another ephemeral port and it should work. Reuse of ephemeral ports won't work without further work.\r\n\r\nI used the term \"ephemeral port\" but my goal is to just obtain an available random port that I will use in this application for multiple URL.\r\nAnd I would add it's a bit disturbing that a URL which is just a string when set to a fix port it behaves in one way and later by getting a random port and building a second URL with that number you cannot achieve the same. Both doesn't give you the same result I would have guessed it worked given the fact `nng` is a _bit_ higher than BSD  socket"}],"action":{"name":"View Issue","url":"https://github.com/nanomsg/nng/issues/907#issuecomment-471836233"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nanomsg/nng/issues/907#issuecomment-471836233",
"url": "https://github.com/nanomsg/nng/issues/907#issuecomment-471836233",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gdamore** [comment]
So the problem is that when we locate the server, we look for a server bound to the same "port".  I believe if you specified "0", you might find that you get attached to the same old server as before.  That might be a mistake.  The use of ephemeral ports (the random ports chosen by the system), and in particular the *reuse* of them, is highly problematic.  For example, if you stop the server, and unbind, that port can wind up getting reused elsewhere.  So you can't really use the same port in that case.

Now you don't see that with websocket.  But in general most of the times you either won't want to reuse the same socket for websocket, or you'll have a well defined port.

This all gets kind of tricky, especially when mixing "specific" port numbers, and random ones.
