### ISSUE TITLE
Drop idempotence requirement from req/rep

### ISSUE THREAD

**Issue by athei** [nanomsg/nng#913]
Req/Rep does automatic re-transmits and the documentation states that therefore all requests are required to be idempotent. Therefore I assume that re-transmits cannot be distinguished from legitimate requests. 

When using req/rep as a RPC I find this a really constraining requirement. Would it be possible to have the protocol prevent double messages being processed at the req site?

I mean we could just generate a unique id per request that all re-transmits share. The req site then only processes the first message with each id its received. Just like TCP sequence numbers.

Or is it already done this way? If so I do not understand the idempotence requirement.

**Comment by gdamore** [comment]
You don't understand the reason for idempotence, I think.  nng can resend, and the idempotence is required to ensure that that no ill effects occur.  We do have message IDs, but the problem is that the server side is stateless.  We could add state, which might help, but would not solve the problem entirely -- because the request could get directed to another req server (for example if the original gets "stuck", or disconnects).  In that case, we have no way to coordinate between servers.  Not only that, but many RPC protocols are inherently idempotent, so it would be a mistake to burden those with a bunch of extra coordination to do something they might not need.

Consequently, idempotence needs to be established at the application layer, not at NNG.  Sorry if this seems unduly constraining, but it's not anything that we're going to change.
