### ISSUE TITLE
in master branch,  NNG_OPT_RECVBUF parameter change to some type other than int ?

### ISSUE THREAD

**Issue by bwlee** [nanomsg/nng#923]
I test with nng master branch,  use nng_setopt_int for NNG_OPT_RECVBUF, NNG_OPT_SENDBUF got  "Incorrect type" error.  

and it is fine in release version.  maybe some typo   @djc

**Comment by gdamore** [comment]
I think these are size_t. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Bowen Li <notifications@github.com> Date: 4/11/19  11:20 PM  (GMT-08:00) To: nanomsg/nng <nng@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [nanomsg/nng] in master branch,  NNG_OPT_RECVBUF parameter change to some type other than int ? (#923) I test with nng master branch,  use nng_setopt_int for NNG_OPT_RECVBUF, NNG_OPT_SENDBUF got  "Incorrect type" error.
and it is fine in release version.  maybe some typo   @djc

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nanomsg/nng","title":"nanomsg/nng","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nanomsg/nng"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"in master branch,  NNG_OPT_RECVBUF parameter change to some type other than int ? (#923)"}],"action":{"name":"View Issue","url":"https://github.com/nanomsg/nng/issues/923"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nanomsg/nng/issues/923",
"url": "https://github.com/nanomsg/nng/issues/923",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gdamore** [comment]
Is there something else needed here?  The type of these options is size_t.

**Comment by neachdainn** [comment]
Seems like this is related to #935?

@gdamore The [documentation][1] does say that they take an `int` and that has been working for me.

[1]: https://nanomsg.github.io/nng/man/tip/nng_options.5.html

**Comment by neachdainn** [comment]
Commenting here instead of #935 for no reason other than this issue is older.

-----

It appears that this issue is that the option is either `size_t` or `int` depending on what protocol you access them on. The "vanilla" socket version [reads/writes an `int`][1] but the SUB version [uses a `size_t`][2]. And, again, the documentation does say that the type is an `int`.

[1]: https://github.com/nanomsg/nng/blob/f723fa9655e1e7fadc1a15b94b66de674ab9fe17/src/core/socket.c#L202
[2]: https://github.com/nanomsg/nng/blob/90467583b7544b68483334070518e29b00ec6d81/src/protocol/pubsub0/sub.c#L433
