### ISSUE TITLE
Using pair is possible to limit the size of messages

### ISSUE THREAD

**Issue by amirouche** [nanomsg/nng#930]
## NNG & Platform details.
GNU / Linux Ubuntu 18.10 nng 1.1.1

## Expected Behavior

It possible to set maxsize to nessage received by a pair

## Actual Behavior

Pair can DoS the remote peer by sending a message that is too big

## Steps to Reproduce

None for the time being

**Comment by codypiersall** [comment]
Hey there!  Are you asking if it's possible to limit the size, or are you saying that you found a bug where the limit is not being respected?  The options are documented here: https://nanomsg.github.io/nng/man/tip/nng_options.5.  The one for adjusting max size is `NNG_OPT_RECVMAXSZ`.  (I believe that `NNG_OPT_RECVMAXSZ` is ignored for `inproc` transport, since anything within your process should be trusted.)

**Comment by amirouche** [comment]
I will check tx.
