### ISSUE TITLE
Any plain to support kcp and pgm transport

### ISSUE THREAD

**Issue by zuowanbushiwo** [nanomsg/nng#933]
PGM  and KCP  can over UDP performs better in latency and also scalability compared to TCP transport, are you going to support?
thanks！

**Comment by gdamore** [comment]
I do have a plan to do this... at KCP over UDP.  Not sure about PGM.  That said, it takes time to implement these things, and $$ speaks. :-)

**Comment by zuowanbushiwo** [comment]
ok，thanks！

**Comment by pde-rent** [comment]
Hi there, I would be very interested in seeing / working on UDP transports as well (notably KCP / PGM / NORM).
I guess a good starting point would be zmq pgm / norm port to here?

**Comment by gdamore** [comment]
KCP support is already planned.  Where it gets "interesting" is handling some of the options like FEC and encryption. 

Adding support for PGM and NORM is a bigger deal, because the underpinnings of the transport layer are currently rather connection oriented.  KCP is thus no problem, but PGM and NORM are a larger challenge.

I do have some design work done to support multicasting (was not really considering PGM, as I've heard nothing but trouble with it from other ZMQ users), but it's not trivial work.

One thing that is different about NNG (and nanomsg in general) vs ZMQ is that NNG allows any pattern to be expressed on top of any transport.  I'd like to retain that, and have some ideas on how to make that "work" even in the face of multicasting.  ZMQ instead chose only to support PUB/SUB with multicasting.

**Comment by gdamore** [comment]
Btw, to accelerate this work, you should contact info@staysail.tech -- we can discuss ways to make this happen sooner rather than later as a sponsored effort.
