### ISSUE TITLE
large message fails with no error message

### ISSUE THREAD

**Issue by luke-titley-dwarf** [nanomsg/nng#954]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

version: v1.1.1
platform centos 7
language: c

## Expected Behavior

nng_sendmsg should report an error when a message fails to send because it is too big, the return value should be non 0.
or
nng_recvmsg should report an error when a message cant be received because it is too big, the return value should be non zero.

## Actual Behavior
No error reported. No way to track down the issue.

## Steps to Reproduce

- Create a pair connection.
- Between two processes.
- Send a large message from one end to the other.
- The message fails to deliver silently.
- Now set nng_setopt_size(socket, NNG_OPT_RECVMAXSZ, 0);
- The message delivers with no problem.

**Comment by codypiersall** [comment]
I do think that it can be confusing whenever you find out for the first time that you're not receiving messages because they're too big, especially if you've been using the same application and just started sending bigger messages.

At this point, I'm not sure that `nng_sendmsg` and `nng_recvmsg` can start returning an error message in this case without breaking backwards compatibility; that's up to Garrett.  And for what it's worth I'm not even sure that `nng_sendmsg` *can* return an error; the dropped message happens on the recv side.

I wonder if there is a way to notify the user *somehow* that this has happened?  Like, when it happens the first time, print something to `stderr`?  You probably wouldn't want to get the message every time, because that just opens up a different type of DOS attack.  That of course adds complexity to the implementation.

**Comment by gdamore** [comment]
Printing to stderr is a nonstarter for a library.

There are statistics available to track this however.

I could possibly be convinced to change the default from 1MB to something else.  I really really believe folks should use these limits (or even smaller) on public networks, but I also know that on private networks these limits cause a lot of extra pain and suffering.

**Comment by luke-titley-dwarf** [comment]
I understand the reason for the limit, and have no problems with it. It's just it took me a day to track down the issue. The application I'm working on is on a private network, so I just set the socket option to 0, but I get this is a bad idea on a public network. I created this particular github issue just to highlight that I think when a message is dropped it should be reported in the return value, either at the sending side or the receiving side. It might not be possible to do that in a minor release, but can it be done in a major ? No worries if not though.

**Comment by gdamore** [comment]
I can't think of any reasonable way to report this back to the caller.  The problem is that to do that, we'd need to actually change the wire protocol.

What would be nice in an update to the protocol(s) is to have this be negotiated so that the sender would know apriori, then we *could* return back something like NNG_EMSGSIZE.

**Comment by gdamore** [comment]
I'm going to change the default message size to 0 (unlimited) with guidance to application developers to set this if to something else on hostile networks.

**Comment by luke-titley-dwarf** [comment]
Hmm, really ? I like the fact that you made the decision to limit the message size by default. In my situation I don't really need it, but it seems right that the safest option is the default. I think this issue could be resolved in the short term with just a mention in nng_recvmsg and nng_sendmsg. Those are the first places I looked when I tried to resolve the issue.

**Comment by gdamore** [comment]
You aren't the first person, but one of many, to be stumped by the large message limit.  Original nanomsg had a wide open default (actually it had no limit, but I added one) which I changed.  In retrospect this has been one of the most common FAQs.

It is also the case that I've never been happy with the 1MB limit.  It was a compromise, and not a very good one.  If your messages are all tiny, then you should set a much smaller limit. 

There's other work that needs to be done to harden nng against malicious peers -- some of which may require protocol changes.  (The concerns are things like starting a negotiation, and then not completing it, leaving the socket stuck open, etc.  These are all DoS style considerations.)
