### ISSUE TITLE
Websocket stream data lost (maybe iov not rewrite)

### ISSUE THREAD

**Issue by qtcdxxyuc** [nanomsg/nng#968]
Note that by filing an issue, you agree that you have read and agreed to
our contribution guidelines.

## NNG & Platform details.

- nng: 1.1.1
- os: ubuntu 18.04LTS
- language: c++

## Expected Behavior

I have a test server that sends a unique id(e.g. `1562306751-b35903-d81c-13743`).It is streaming and is sent until the client disconnects.When I use `nng_steam_recv`,find a special situation.

> log

```c++
I0705 14:05:49.870645  7627 base.cpp:164]recv(31):1562306749-b35903-d81c-13739
I0705 14:05:49.870739  7627 base.cpp:164]recv(31):                                
I0705 14:05:49.870980  7627 base.cpp:164]recv(31):1562306749-b35903-d81c-13741
```

Some data lost,but they size is true.

> client.cpp

```c++
int rv;
nng_aio *aio = nullptr;
nng_url *url = nullptr;
nng_stream_dialer *stream_dialer = nullptr;

rv = nng_aio_alloc(&aio, nullptr, nullptr);
LOG_ASSERT(!rv) << "aio alloc error: " << nng_strerror(rv); 
rv = nng_url_parse(&url, "ws://192.168.3.66:50051");
LOG_ASSERT(!rv) << "url parse error: " << nng_strerror(rv); 
rv = nng_stream_dialer_alloc_url(&stream_dialer, url);
LOG_ASSERT(!rv) << "stream dialer alloc error: " << nng_strerror(rv); 

nng_stream_dialer_dial(stream_dialer, aio);
nng_aio_wait(aio);
rv = nng_aio_result(aio);
if (rv != 0) { LOG(FATAL) << "aio accept error: " << nng_strerror(rv); }

nng_stream *stream = static_cast<nng_stream *>(nng_aio_get_output(aio, 0));
if (!stream) { LOG(FATAL) << "stream is null ptr"; }

//using for Multithreading recv
auto stream_ptr = std::shared_ptr<nng_stream>(stream, [](nng_stream *s) {
    nng_stream_close(s);
    nng_stream_free(s);
});

auto recv_func = [stream_ptr]() {
    int rv = 0;
    nng_aio *aio = nullptr;
    nng_iov iov;
    char buf[64];
    iov.iov_buf = buf;
    iov.iov_len = 64;

    rv = nng_aio_alloc(&aio, post_baton, &baton);
    LOG_ASSERT(!rv) <<  "aio alloc error: " << nng_strerror(rv);

    while (true){
        memset(buf, 0, 64);
        rv = nng_aio_set_iov(aio, 1, &iov);
        LOG_ASSERT(!rv) << "aio set iov error: " << nng_strerror(rv);

        nng_stream_recv(stream_ptr.get(), aio);
        nng_aio_wait(aio);
        rv = nng_aio_result(aio);
        LOG_ASSERT(!rv) << "aio recv error: " << nng_strerror(rv);

        std::string_view result(buf, nng_aio_count(aio));
        LOG(INFO)<< " recv(" << result.size() << "): " << result;
    }
};

recv_func();
```

The phenomenon of losing data is random.When I use multiple threads to execute ` recv_func`,basically won't be lost.It should be said that it is not data loss, but `nng` has not modified `iov`.I have tried different `memset`.

My server uses `nng` implementation, I tried the `javascript` and `lua`,the phenomenon is consistent.When I connect to my server using other clients(`cpprest`,`lua`,`js`), the data they receive is correct.

> server.cpp

```c++
int rv;
nng_aio *aio = nullptr;
nng_url *url = nullptr;
nng_stream_listener *stream_listener = nullptr;

rv = nng_url_parse(&url, "ws://192.168.3.66:50051");
LOG_ASSERT(!rv) << "url parse error: " << nng_strerror(rv); 
rv = nng_stream_listener_alloc_url(&stream_listener, url);
LOG_ASSERT(!rv) << "stream listener alloc error: " << nng_strerror(rv); 
rv = nng_stream_listener_listen(stream_listener);
LOG_ASSERT(!rv) << "stream listener listen error: " << nng_strerror(rv);

while(true) {
    rv = nng_aio_alloc(&aio, nullptr, nullptr);
    LOG_ASSERT(!rv) << "aio alloc error: " << nng_strerror(rv); 

    nng_stream_listener_accept(stream_listener, aio);
    nng_aio_wait(aio);
    rv = nng_aio_result(aio);
    LOG_ASSERT(!rv) << "aio accept error: " << nng_strerror(rv); 

    nng_stream *stream = static_cast<nng_stream *>(nng_aio_get_output(aio, 0));
    LOG_ASSERT(stream) << "stream is null ptr"; 

    auto stream_ptr = std::shared_ptr<nng_stream>(stream, [](nng_stream *s) {
        nng_stream_close(s);
        nng_stream_free(s);
    });

    auto recv_func = [stream_ptr](){
        int rv;
        nng_iov iov;
        nng_aio *aio = nullptr;
        rv = nng_aio_alloc(&aio, nullptr, nullptr);
        LOG_ASSERT(!rv) << "aio alloc error: " << nng_strerror(rv);
        while (true) {
            //oid is unique id.
            auto oid_str = ecv::OID::Create().ToPrettyString();
            iov.iov_buf = oid_str.data();
            iov.iov_len = oid_str.size();
            rv = nng_aio_set_iov(aio, 1, &iov);
            LOG_ASSERT(!rv) << "aio set iov error: " << nng_strerror(rv);
            LOG(INFO) << "send: " << oid_str;
            nng_stream_send(stream_ptr.get(), aio);
            nng_aio_wait(aio);
            rv = nng_aio_result(aio);
            if (rv != 0) {
                LOG(ERROR) << "aio send error: " << nng_strerror(rv);
                break;
            }
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
        nng_aio_free(aio);	//free recv-aio
    };

    std::vector<std::thread> thread_vec;
    //Even if set to single-threaded writes, it will happen
    for(int i=0;i<4;i++){
        thread_vec.push_back(std::thread(recv_func));
    }

    for(auto& t: thread_vec){
        t.join();
    }
    nng_aio_free(aio);	//free handle-aio
}
```

## Actual Behavior

`Nng` should correctly rewrite `iov` to make the data correct.

## Steps to Reproduce

see `Expected Behavior`.

**Comment by gdamore** [comment]
Because you're setting the iov each time, it should be fine.

One thing that you're doing wrong is not coping with the possibility of getting less data than you asked for.  Depending on the underlying network stack, the nng_stream_recv() will not block until the entire iov is filled, but instead will block until it has received *any* data.

Typically what you have to do in that circumstance is advance the iov a bit (the number of bytes you already got), and decrement the iov buffer size by the amount you already received.

This is just like a non-blocking receive.

What might be useful would be to create an nng_stream_receive_all() function that did this for you, reposting the receive until you've gotten all the bytes you've asked for.

**Comment by gdamore** [comment]
I see you're printing the result of nng_aio_count(), and that doesn't seem to match.  I'll have to investigate more closely.

**Comment by qtcdxxyuc** [comment]
Does the `nng_stream_recv`  mean ?

- block util any data recv or iov filled.

Iov correct usage:

- collect data that has been received
- modify iov_size = total_size - recved_size
- until collect all data

Does that mean that I need to identify the total length of this frame of data before each communication?

**Comment by gdamore** [comment]
nng_stream_recv will block until any data is received.  It does not wait for the entire iov to be completed.

Yes, you need to modify the length for each time, accounting for the data you've already received.

**Comment by gdamore** [comment]
I'm also looking a bit more closely at your code, and I see it looks like you create multiple threads to handle receives on the same stream.  That's not going to necessarily work the way you'd like it to.  Accesses to a single stream should really be single threaded -- as data can arrive out of order, etc.  due to changes in the stream scheduling.  There really isn't a clear way to identify which bytes were sent or received, and the data may well be scrambled.

This is a general attribute of streams -- you don't want to access them from multiple threads.  That's true for TCP, IPC, etc., and it's also true for nng_stream objects.

Note that nng_socket objects, which represent message oriented sockets, *do* support concurrent access, but that's because they deal with arbitrating order, and serializing as necessary, on top of the underlying stream objects.  When you use nng_stream, you bypass that entire set of logic.

In order to really proceed here, I'd like to see some single threaded examples -- ideally in C rather than C++ as its harder for me to reason about the C++ (partly because my C++ knowledge is very dated and the language has a lot of side effects etc. that can change behaviors.  The explicit nature of C makes it better for problem reproduction.)

**Comment by qtcdxxyuc** [comment]
In fact, I originally wrote it using the coroutine(fiber) method. It also has this problem. I think the thread is better understood and the thread is used in the case. Later I try to use single-threaded c to indicate this problem.

**Comment by qtcdxxyuc** [comment]
I may know this question. In fact, whether it is a coroutine model or a thread model, it will lead to a special situation.

```c
nng_stream_send();
//wait for aio callback;
//The waiting process does not block other threads/coroutines.
nng_stream_result();
```

It may result in multiple occurrences of send and then multiple waits in one stream.Then I tried to send a single thread to the stream.This seems no problem.Stream is lower than I thought.

Sometimes we want to use websocket to communicate with the browser,  then this does not require nng_ protocol. Or we have to rewrite our own underlying design with a stream interface like this?

**Comment by gdamore** [comment]
You can use nng_stream to communicate with a remote websocket peer.  What you cannot do is reliably do so on the *same* stream from different threads simultaneously.  That makes no sense, because the data can be scrambled.

NNG protocol uses its own framing to and orchestration to prevent this when using NNG messages, so messages won't be interleaved improperly.  If you're not using the NNG protocol then you have to do this in your own application code.

**Comment by qtcdxxyuc** [comment]
Thank you.
