### ISSUE TITLE
nng_setopt_size for send buffer

### ISSUE THREAD

**Issue by NissimHadar** [nanomsg/nng#977]
Hi,
I am migrating from nanomsg to nng and found the following code:

```// Make sure the send buffer is big enough for our images.
    int opt = 1024 * 1024 * 16;
    nn_setsockopt( image_pub, NN_SOL_SOCKET, NN_SNDBUF, &opt, sizeof( opt ) );
```
I cannot find a way to do this in nng.
Do I need to do this?

Thanks!!!

**Comment by gdamore** [comment]
NoSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: NissimHadar <notifications@github.com> Date: 8/9/19  8:03 AM  (GMT-08:00) To: nanomsg/nng <nng@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [nanomsg/nng] nng_setopt_size for send buffer (#977) Hi,
I am migrating from nanomsg to nng and found the following code:
    int opt = 1024 * 1024 * 16;
    nn_setsockopt( image_pub, NN_SOL_SOCKET, NN_SNDBUF, &opt, sizeof( opt ) );

I cannot find a way to do this in nng.
Do I need to do this?
Thanks!!!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nanomsg/nng/issues/977?email_source=notifications\u0026email_token=AAJ4G7IZECUNLBP25RUNYHDQDWBM3A5CNFSM4IKU4EN2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HENO67A",
"url": "https://github.com/nanomsg/nng/issues/977?email_source=notifications\u0026email_token=AAJ4G7IZECUNLBP25RUNYHDQDWBM3A5CNFSM4IKU4EN2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HENO67A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gdamore** [comment]
No. 

This particular socket option is used to set up buffering space, but generally you should not need to tune this for NNG, unless you have unusual needs.

**Comment by NissimHadar** [comment]
Thanks!  We are sending 8K by 6K video (albeit,compressed and at a low
rate) between remote systems.  We do want to reach 30 Hz.

**Comment by gdamore** [comment]
I hope compressed!  This is about 1.1 Gigabits per frame (assuming 24 bit color).  From my perspective this is a high bandwidth application at 30 Hz.  I'm not sure how well compressed these frames are, but the worst case is very bad indeed, at about 34-35 Gbps!

Consequently, it may be wothwhile to discuss options to tune NNG for this use case.  We can help you -- contact us at info@staysail.tech if you want to discuss options.
