### ISSUE TITLE
How could I write a async server using nng?

### ISSUE THREAD

**Issue by smartseal** [nanomsg/nng#998]
I tried demo/async example and still have confusions. Hope you can help me clear:

I want to write a high performance server.
The server accept client request and make response to the client. In addition, server may response a client request for several times depending on the request state. 

For example , the client make a order, the server keep the order and make the first response. Then the status of the order is changed, server will update the new order status to client.

In this senario, I should use req/rep protocol, ok?

But how can I find the client which to update the order status? The work stucture of demo/async may be reused by other client, right?

**Comment by gdamore** [comment]
The demo/async program does does almost exactly this.  What you need to do is create a context (nng_ctx_open()) on the server, and then you use that context to identify the request.  Each context you have open should only be processing a single request at a time, but you may have many such contexts open on a single socket.  NNG will handle figuring out which client to send the response to you, provided you use the context correctly.

One key difference here is that REQ/REP has a one-to-one relationship between request and reply (mostly) -- meaning it is not possible for a server to send multiple replies to a single request.  That would break the state machine.

I'm not sure if that helps, but generally you should try to cast things so that the the client issues a new request if it is going to need more data.  If that depends on the reply coming from the server, than the reply should include information to that effect to inform your client.

**Comment by smartseal** [comment]
thanks for response. I am not quite familiar with nng. It seems req/rep is not the kind of protocol I should use.

Can the same socket bind to different kind of protocol? such as req/rep and sub/pub?

**Comment by gdamore** [comment]
You can only use a single protocol per socket.

**Comment by KrishnaPG** [comment]
@smartseal here is something that may help:

- setup the server as req/rep
- when a request is received create a new _publish point_ specific to that request, and reply that pub-point to the client
- client will subscribe to the pub-point
- sever will keep posting the further updates to the pub-point for that particular request. (The original req/rep will be closed, just like http)

@gdamore Regarding servers, and performance, it would be great if some kind of performance metrics were available anywhere. For example, [seaStar](https://github.com/scylladb/seastar) is high-performance native socket server (in C++). Would love to see how NNG compares with likes of such, and more importantly how the performance improved over the ages from zeroMQ to NanoMsg to NNG. There must be a good reason if large efforts went into redesigning it over a period of time, and we would like to learn more on how performance gained in the process.

**Comment by gdamore** [comment]
@KrishnaPG The main motivation for changing was not to improve performance.   I've got a long discussion of the motivations online, which you can find pretty easily.

However, it does improve *scalability*, and for *real-world* applications performance as well (due to fewer system calls.)

At some point I'll probably drum up some benchmark data; it's not at the top of my priority list.
